services:
  neko:
    image: neko-chrome-dev
    container_name: neko-chrome-dev
    restart: unless-stopped
    shm_size: "${SHM_SIZE:-2gb}"
    ports:
      - "${HOST_PORT:-8080}:8080"
      - "${NEKO_WEBRTC_EPR:-52000-52100}:${NEKO_WEBRTC_EPR:-52000-52100}/udp"
    environment:
      - NEKO_DESKTOP_SCREEN=${NEKO_DESKTOP_SCREEN}
      - NEKO_MEMBER_MULTIUSER_USER_PASSWORD=${NEKO_USER_PASSWORD}
      - NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD=${NEKO_ADMIN_PASSWORD}
      - NEKO_WEBRTC_EPR=${NEKO_WEBRTC_EPR}
      - NEKO_WEBRTC_ICELITE=${NEKO_WEBRTC_ICELITE}
      - NEKO_NAT1TO1=${NEKO_NAT1TO1}
      - NEKO_FILETRANSFER_ENABLED=true
      - NEKO_FILETRANSFER_DIR=/home/neko/Downloads
      - NEKO_WEBRTC_VIDEO_CODEC=${NEKO_VIDEO_CODEC}
      - NEKO_WEBRTC_VIDEO_BITRATE=${NEKO_VIDEO_BITRATE}
      - NEKO_WEBRTC_MAX_FPS=${NEKO_MAX_FPS}
      - NEKO_WEBRTC_AUDIO_CODEC=${NEKO_AUDIO_CODEC}
      - NEKO_WEBRTC_AUDIO_BITRATE=${NEKO_AUDIO_BITRATE}
      # HTTP Proxy
      - HTTP_PROXY=${HTTP_PROXY:-""}
      - HTTPS_PROXY=${HTTPS_PROXY:-""}
      - NO_PROXY=${NO_PROXY:-""}
    volumes:
      - ./data/downloads:/home/neko/Downloads
