# This Dockerfile is pre-processed by the ./docker script, it is not meant to be used directly.

FROM ./runtime/xorg-deps/ AS xorg-deps
FROM ./server/ AS server
FROM ./client/ AS client
FROM ./runtime/$RUNTIME_DOCKERFILE AS runtime

COPY --from=xorg-deps /usr/local/lib/xorg/modules/drivers/dummy_drv.so /usr/lib/xorg/modules/drivers/dummy_drv.so
COPY --from=xorg-deps /usr/local/lib/xorg/modules/input/neko_drv.so /usr/lib/xorg/modules/input/neko_drv.so
COPY --from=server /src/bin/plugins/ /etc/neko/plugins/
COPY --from=server /src/bin/neko /usr/bin/neko
COPY --from=client /src/dist/ /var/www

COPY config.yml /etc/neko/neko.yaml
