#!/bin/bash
cd "$(dirname "$0")"

#
# aborting if any command returns a non-zero value
set -e

GIT_COMMIT=`git rev-parse --short HEAD`
GIT_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`

docker build -t neko_server_build --target build --build-arg "GIT_COMMIT=$GIT_COMMIT" --build-arg "GIT_BRANCH=$GIT_BRANCH" ..
docker build -t neko_server_runtime --target runtime --build-arg "GIT_COMMIT=$GIT_COMMIT" --build-arg "GIT_BRANCH=$GIT_BRANCH" ..

docker build -t neko_server_app --build-arg "BASE_IMAGE=neko_server_runtime" ./runtime
