export const keywords: { [name: string]: string[] } = {
  '100': ['score', 'perfect', 'numbers', 'century', 'exam', 'quiz', 'test', 'pass', 'hundred'],
  '1234': ['numbers', 'blue-square'],
  grinning: ['face', 'smile', 'happy', 'joy', ':D', 'grin'],
  grimacing: ['face', 'grimace', 'teeth'],
  grin: ['face', 'happy', 'smile', 'joy', 'kawaii'],
  joy: ['face', 'cry', 'tears', 'weep', 'happy', 'happytears', 'haha'],
  rofl: ['face', 'rolling', 'floor', 'laughing', 'lol', 'haha'],
  partying: ['face', 'celebration', 'woohoo'],
  smiley: ['face', 'happy', 'joy', 'haha', ':D', ':)', 'smile', 'funny'],
  smile: ['face', 'happy', 'joy', 'funny', 'haha', 'laugh', 'like', ':D', ':)'],
  sweat_smile: ['face', 'hot', 'happy', 'laugh', 'sweat', 'smile', 'relief'],
  laughing: ['happy', 'joy', 'lol', 'satisfied', 'haha', 'face', 'glad', 'XD', 'laugh'],
  innocent: ['face', 'angel', 'heaven', 'halo'],
  wink: ['face', 'happy', 'mischievous', 'secret', ';)', 'smile', 'eye'],
  blush: ['face', 'smile', 'happy', 'flushed', 'crush', 'embarrassed', 'shy', 'joy'],
  slightly_smiling_face: ['face', 'smile'],
  upside_down_face: ['face', 'flipped', 'silly', 'smile'],
  relaxed: ['face', 'blush', 'massage', 'happiness'],
  yum: ['happy', 'joy', 'tongue', 'smile', 'face', 'silly', 'yummy', 'nom', 'delicious', 'savouring'],
  relieved: ['face', 'relaxed', 'phew', 'massage', 'happiness'],
  heart_eyes: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart'],
  smiling_face_with_three_hearts: [
    'face',
    'love',
    'like',
    'affection',
    'valentines',
    'infatuation',
    'crush',
    'hearts',
    'adore',
  ],
  kissing_heart: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss'],
  kissing: ['love', 'like', 'face', '3', 'valentines', 'infatuation', 'kiss'],
  kissing_smiling_eyes: ['face', 'affection', 'valentines', 'infatuation', 'kiss'],
  kissing_closed_eyes: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss'],
  stuck_out_tongue_winking_eye: ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'wink', 'tongue'],
  zany: ['face', 'goofy', 'crazy'],
  raised_eyebrow: ['face', 'distrust', 'scepticism', 'disapproval', 'disbelief', 'surprise'],
  monocle: ['face', 'stuffy', 'wealthy'],
  stuck_out_tongue_closed_eyes: ['face', 'prank', 'playful', 'mischievous', 'smile', 'tongue'],
  stuck_out_tongue: ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'tongue'],
  money_mouth_face: ['face', 'rich', 'dollar', 'money'],
  nerd_face: ['face', 'nerdy', 'geek', 'dork'],
  sunglasses: ['face', 'cool', 'smile', 'summer', 'beach', 'sunglass'],
  star_struck: ['face', 'smile', 'starry', 'eyes', 'grinning'],
  clown_face: ['face'],
  cowboy_hat_face: ['face', 'cowgirl', 'hat'],
  hugs: ['face', 'smile', 'hug'],
  smirk: ['face', 'smile', 'mean', 'prank', 'smug', 'sarcasm'],
  no_mouth: ['face', 'hellokitty'],
  neutral_face: ['indifference', 'meh', ':|', 'neutral'],
  expressionless: ['face', 'indifferent', '-_-', 'meh', 'deadpan'],
  unamused: [
    'indifference',
    'bored',
    'straight face',
    'serious',
    'sarcasm',
    'unimpressed',
    'skeptical',
    'dubious',
    'side_eye',
  ],
  roll_eyes: ['face', 'eyeroll', 'frustrated'],
  thinking: ['face', 'hmmm', 'think', 'consider'],
  lying_face: ['face', 'lie', 'pinocchio'],
  hand_over_mouth: ['face', 'whoops', 'shock', 'surprise'],
  shushing: ['face', 'quiet', 'shhh'],
  symbols_over_mouth: ['face', 'swearing', 'cursing', 'cussing', 'profanity', 'expletive'],
  exploding_head: ['face', 'shocked', 'mind', 'blown'],
  flushed: ['face', 'blush', 'shy', 'flattered'],
  disappointed: ['face', 'sad', 'upset', 'depressed', ':('],
  worried: ['face', 'concern', 'nervous', ':('],
  angry: ['mad', 'face', 'annoyed', 'frustrated'],
  rage: ['angry', 'mad', 'hate', 'despise'],
  pensive: ['face', 'sad', 'depressed', 'upset'],
  confused: ['face', 'indifference', 'huh', 'weird', 'hmmm', ':/'],
  slightly_frowning_face: ['face', 'frowning', 'disappointed', 'sad', 'upset'],
  frowning_face: ['face', 'sad', 'upset', 'frown'],
  persevere: ['face', 'sick', 'no', 'upset', 'oops'],
  confounded: ['face', 'confused', 'sick', 'unwell', 'oops', ':S'],
  tired_face: ['sick', 'whine', 'upset', 'frustrated'],
  weary: ['face', 'tired', 'sleepy', 'sad', 'frustrated', 'upset'],
  pleading: ['face', 'begging', 'mercy'],
  triumph: ['face', 'gas', 'phew', 'proud', 'pride'],
  open_mouth: ['face', 'surprise', 'impressed', 'wow', 'whoa', ':O'],
  scream: ['face', 'munch', 'scared', 'omg'],
  fearful: ['face', 'scared', 'terrified', 'nervous', 'oops', 'huh'],
  cold_sweat: ['face', 'nervous', 'sweat'],
  hushed: ['face', 'woo', 'shh'],
  frowning: ['face', 'aw', 'what'],
  anguished: ['face', 'stunned', 'nervous'],
  cry: ['face', 'tears', 'sad', 'depressed', 'upset', ":'("],
  disappointed_relieved: ['face', 'phew', 'sweat', 'nervous'],
  drooling_face: ['face'],
  sleepy: ['face', 'tired', 'rest', 'nap'],
  sweat: ['face', 'hot', 'sad', 'tired', 'exercise'],
  hot: ['face', 'feverish', 'heat', 'red', 'sweating'],
  cold: ['face', 'blue', 'freezing', 'frozen', 'frostbite', 'icicles'],
  sob: ['face', 'cry', 'tears', 'sad', 'upset', 'depressed'],
  dizzy_face: ['spent', 'unconscious', 'xox', 'dizzy'],
  astonished: ['face', 'xox', 'surprised', 'poisoned'],
  zipper_mouth_face: ['face', 'sealed', 'zipper', 'secret'],
  nauseated_face: ['face', 'vomit', 'gross', 'green', 'sick', 'throw up', 'ill'],
  sneezing_face: ['face', 'gesundheit', 'sneeze', 'sick', 'allergy'],
  vomiting: ['face', 'sick'],
  mask: ['face', 'sick', 'ill', 'disease'],
  face_with_thermometer: ['sick', 'temperature', 'thermometer', 'cold', 'fever'],
  face_with_head_bandage: ['injured', 'clumsy', 'bandage', 'hurt'],
  woozy: ['face', 'dizzy', 'intoxicated', 'tipsy', 'wavy'],
  sleeping: ['face', 'tired', 'sleepy', 'night', 'zzz'],
  zzz: ['sleepy', 'tired', 'dream'],
  poop: ['hankey', 'shitface', 'fail', 'turd', 'shit'],
  smiling_imp: ['devil', 'horns'],
  imp: ['devil', 'angry', 'horns'],
  japanese_ogre: ['monster', 'red', 'mask', 'halloween', 'scary', 'creepy', 'devil', 'demon', 'japanese', 'ogre'],
  japanese_goblin: ['red', 'evil', 'mask', 'monster', 'scary', 'creepy', 'japanese', 'goblin'],
  skull: ['dead', 'skeleton', 'creepy', 'death'],
  ghost: ['halloween', 'spooky', 'scary'],
  alien: ['UFO', 'paul', 'weird', 'outer_space'],
  robot: ['computer', 'machine', 'bot'],
  smiley_cat: ['animal', 'cats', 'happy', 'smile'],
  smile_cat: ['animal', 'cats', 'smile'],
  joy_cat: ['animal', 'cats', 'haha', 'happy', 'tears'],
  heart_eyes_cat: ['animal', 'love', 'like', 'affection', 'cats', 'valentines', 'heart'],
  smirk_cat: ['animal', 'cats', 'smirk'],
  kissing_cat: ['animal', 'cats', 'kiss'],
  scream_cat: ['animal', 'cats', 'munch', 'scared', 'scream'],
  crying_cat_face: ['animal', 'tears', 'weep', 'sad', 'cats', 'upset', 'cry'],
  pouting_cat: ['animal', 'cats'],
  palms_up: ['hands', 'gesture', 'cupped', 'prayer'],
  raised_hands: ['gesture', 'hooray', 'yea', 'celebration', 'hands'],
  clap: ['hands', 'praise', 'applause', 'congrats', 'yay'],
  wave: ['hands', 'gesture', 'goodbye', 'solong', 'farewell', 'hello', 'hi', 'palm'],
  call_me_hand: ['hands', 'gesture'],
  '+1': ['thumbsup', 'yes', 'awesome', 'good', 'agree', 'accept', 'cool', 'hand', 'like'],
  '-1': ['thumbsdown', 'no', 'dislike', 'hand'],
  facepunch: ['angry', 'violence', 'fist', 'hit', 'attack', 'hand'],
  fist: ['fingers', 'hand', 'grasp'],
  fist_left: ['hand', 'fistbump'],
  fist_right: ['hand', 'fistbump'],
  v: ['fingers', 'ohyeah', 'hand', 'peace', 'victory', 'two'],
  ok_hand: ['fingers', 'limbs', 'perfect', 'ok', 'okay'],
  raised_hand: ['fingers', 'stop', 'highfive', 'palm', 'ban'],
  raised_back_of_hand: ['fingers', 'raised', 'backhand'],
  open_hands: ['fingers', 'butterfly', 'hands', 'open'],
  muscle: ['arm', 'flex', 'hand', 'summer', 'strong', 'biceps'],
  pray: ['please', 'hope', 'wish', 'namaste', 'highfive'],
  foot: ['kick', 'stomp'],
  leg: ['kick', 'limb'],
  handshake: ['agreement', 'shake'],
  point_up: ['hand', 'fingers', 'direction', 'up'],
  point_up_2: ['fingers', 'hand', 'direction', 'up'],
  point_down: ['fingers', 'hand', 'direction', 'down'],
  point_left: ['direction', 'fingers', 'hand', 'left'],
  point_right: ['fingers', 'hand', 'direction', 'right'],
  fu: ['hand', 'fingers', 'rude', 'middle', 'flipping'],
  raised_hand_with_fingers_splayed: ['hand', 'fingers', 'palm'],
  love_you: ['hand', 'fingers', 'gesture'],
  metal: ['hand', 'fingers', 'evil_eye', 'sign_of_horns', 'rock_on'],
  crossed_fingers: ['good', 'lucky'],
  vulcan_salute: ['hand', 'fingers', 'spock', 'star trek'],
  writing_hand: ['lower_left_ballpoint_pen', 'stationery', 'write', 'compose'],
  selfie: ['camera', 'phone'],
  nail_care: ['beauty', 'manicure', 'finger', 'fashion', 'nail'],
  lips: ['mouth', 'kiss'],
  tooth: ['teeth', 'dentist'],
  tongue: ['mouth', 'playful'],
  ear: ['face', 'hear', 'sound', 'listen'],
  nose: ['smell', 'sniff'],
  eye: ['face', 'look', 'see', 'watch', 'stare'],
  eyes: ['look', 'watch', 'stalk', 'peek', 'see'],
  brain: ['smart', 'intelligent'],
  bust_in_silhouette: ['user', 'person', 'human'],
  busts_in_silhouette: ['user', 'person', 'human', 'group', 'team'],
  speaking_head: ['user', 'person', 'human', 'sing', 'say', 'talk'],
  baby: ['child', 'boy', 'girl', 'toddler'],
  child: ['gender-neutral', 'young'],
  boy: ['man', 'male', 'guy', 'teenager'],
  girl: ['female', 'woman', 'teenager'],
  adult: ['gender-neutral', 'person'],
  man: ['mustache', 'father', 'dad', 'guy', 'classy', 'sir', 'moustache'],
  woman: ['female', 'girls', 'lady'],
  blonde_woman: ['woman', 'female', 'girl', 'blonde', 'person'],
  blonde_man: ['man', 'male', 'boy', 'blonde', 'guy', 'person'],
  bearded_person: ['person', 'bewhiskered'],
  older_adult: ['human', 'elder', 'senior', 'gender-neutral'],
  older_man: ['human', 'male', 'men', 'old', 'elder', 'senior'],
  older_woman: ['human', 'female', 'women', 'lady', 'old', 'elder', 'senior'],
  man_with_gua_pi_mao: ['male', 'boy', 'chinese'],
  woman_with_headscarf: ['female', 'hijab', 'mantilla', 'tichel'],
  woman_with_turban: ['female', 'indian', 'hinduism', 'arabs', 'woman'],
  man_with_turban: ['male', 'indian', 'hinduism', 'arabs'],
  policewoman: ['woman', 'police', 'law', 'legal', 'enforcement', 'arrest', '911', 'female'],
  policeman: ['man', 'police', 'law', 'legal', 'enforcement', 'arrest', '911'],
  construction_worker_woman: ['female', 'human', 'wip', 'build', 'construction', 'worker', 'labor', 'woman'],
  construction_worker_man: ['male', 'human', 'wip', 'guy', 'build', 'construction', 'worker', 'labor'],
  guardswoman: ['uk', 'gb', 'british', 'female', 'royal', 'woman'],
  guardsman: ['uk', 'gb', 'british', 'male', 'guy', 'royal'],
  female_detective: ['human', 'spy', 'detective', 'female', 'woman'],
  male_detective: ['human', 'spy', 'detective'],
  woman_health_worker: ['doctor', 'nurse', 'therapist', 'healthcare', 'woman', 'human'],
  man_health_worker: ['doctor', 'nurse', 'therapist', 'healthcare', 'man', 'human'],
  woman_farmer: ['rancher', 'gardener', 'woman', 'human'],
  man_farmer: ['rancher', 'gardener', 'man', 'human'],
  woman_cook: ['chef', 'woman', 'human'],
  man_cook: ['chef', 'man', 'human'],
  woman_student: ['graduate', 'woman', 'human'],
  man_student: ['graduate', 'man', 'human'],
  woman_singer: ['rockstar', 'entertainer', 'woman', 'human'],
  man_singer: ['rockstar', 'entertainer', 'man', 'human'],
  woman_teacher: ['instructor', 'professor', 'woman', 'human'],
  man_teacher: ['instructor', 'professor', 'man', 'human'],
  woman_factory_worker: ['assembly', 'industrial', 'woman', 'human'],
  man_factory_worker: ['assembly', 'industrial', 'man', 'human'],
  woman_technologist: [
    'coder',
    'developer',
    'engineer',
    'programmer',
    'software',
    'woman',
    'human',
    'laptop',
    'computer',
  ],
  man_technologist: ['coder', 'developer', 'engineer', 'programmer', 'software', 'man', 'human', 'laptop', 'computer'],
  woman_office_worker: ['business', 'manager', 'woman', 'human'],
  man_office_worker: ['business', 'manager', 'man', 'human'],
  woman_mechanic: ['plumber', 'woman', 'human', 'wrench'],
  man_mechanic: ['plumber', 'man', 'human', 'wrench'],
  woman_scientist: ['biologist', 'chemist', 'engineer', 'physicist', 'woman', 'human'],
  man_scientist: ['biologist', 'chemist', 'engineer', 'physicist', 'man', 'human'],
  woman_artist: ['painter', 'woman', 'human'],
  man_artist: ['painter', 'man', 'human'],
  woman_firefighter: ['fireman', 'woman', 'human'],
  man_firefighter: ['fireman', 'man', 'human'],
  woman_pilot: ['aviator', 'plane', 'woman', 'human'],
  man_pilot: ['aviator', 'plane', 'man', 'human'],
  woman_astronaut: ['space', 'rocket', 'woman', 'human'],
  man_astronaut: ['space', 'rocket', 'man', 'human'],
  woman_judge: ['justice', 'court', 'woman', 'human'],
  man_judge: ['justice', 'court', 'man', 'human'],
  woman_superhero: ['woman', 'female', 'good', 'heroine', 'superpowers'],
  man_superhero: ['man', 'male', 'good', 'hero', 'superpowers'],
  woman_supervillain: ['woman', 'female', 'evil', 'bad', 'criminal', 'heroine', 'superpowers'],
  man_supervillain: ['man', 'male', 'evil', 'bad', 'criminal', 'hero', 'superpowers'],
  mrs_claus: ['woman', 'female', 'xmas', 'mother christmas'],
  santa: ['festival', 'man', 'male', 'xmas', 'father christmas'],
  sorceress: ['woman', 'female', 'mage', 'witch'],
  wizard: ['man', 'male', 'mage', 'sorcerer'],
  woman_elf: ['woman', 'female'],
  man_elf: ['man', 'male'],
  woman_vampire: ['woman', 'female'],
  man_vampire: ['man', 'male', 'dracula'],
  woman_zombie: ['woman', 'female', 'undead', 'walking dead'],
  man_zombie: ['man', 'male', 'dracula', 'undead', 'walking dead'],
  woman_genie: ['woman', 'female'],
  man_genie: ['man', 'male'],
  mermaid: ['woman', 'female', 'merwoman', 'ariel'],
  merman: ['man', 'male', 'triton'],
  woman_fairy: ['woman', 'female'],
  man_fairy: ['man', 'male'],
  angel: ['heaven', 'wings', 'halo'],
  pregnant_woman: ['baby'],
  breastfeeding: ['nursing', 'baby'],
  princess: ['girl', 'woman', 'female', 'blond', 'crown', 'royal', 'queen'],
  prince: ['boy', 'man', 'male', 'crown', 'royal', 'king'],
  bride_with_veil: ['couple', 'marriage', 'wedding', 'woman', 'bride'],
  man_in_tuxedo: ['couple', 'marriage', 'wedding', 'groom'],
  running_woman: ['woman', 'walking', 'exercise', 'race', 'running', 'female'],
  running_man: ['man', 'walking', 'exercise', 'race', 'running'],
  walking_woman: ['human', 'feet', 'steps', 'woman', 'female'],
  walking_man: ['human', 'feet', 'steps'],
  dancer: ['female', 'girl', 'woman', 'fun'],
  man_dancing: ['male', 'boy', 'fun', 'dancer'],
  dancing_women: ['female', 'bunny', 'women', 'girls'],
  dancing_men: ['male', 'bunny', 'men', 'boys'],
  couple: ['pair', 'people', 'human', 'love', 'date', 'dating', 'like', 'affection', 'valentines', 'marriage'],
  two_men_holding_hands: ['pair', 'couple', 'love', 'like', 'bromance', 'friendship', 'people', 'human'],
  two_women_holding_hands: ['pair', 'friendship', 'couple', 'love', 'like', 'female', 'people', 'human'],
  bowing_woman: ['woman', 'female', 'girl'],
  bowing_man: ['man', 'male', 'boy'],
  man_facepalming: ['man', 'male', 'boy', 'disbelief'],
  woman_facepalming: ['woman', 'female', 'girl', 'disbelief'],
  woman_shrugging: ['woman', 'female', 'girl', 'confused', 'indifferent', 'doubt'],
  man_shrugging: ['man', 'male', 'boy', 'confused', 'indifferent', 'doubt'],
  tipping_hand_woman: ['female', 'girl', 'woman', 'human', 'information'],
  tipping_hand_man: ['male', 'boy', 'man', 'human', 'information'],
  no_good_woman: ['female', 'girl', 'woman', 'nope'],
  no_good_man: ['male', 'boy', 'man', 'nope'],
  ok_woman: ['women', 'girl', 'female', 'pink', 'human', 'woman'],
  ok_man: ['men', 'boy', 'male', 'blue', 'human', 'man'],
  raising_hand_woman: ['female', 'girl', 'woman'],
  raising_hand_man: ['male', 'boy', 'man'],
  pouting_woman: ['female', 'girl', 'woman'],
  pouting_man: ['male', 'boy', 'man'],
  frowning_woman: ['female', 'girl', 'woman', 'sad', 'depressed', 'discouraged', 'unhappy'],
  frowning_man: ['male', 'boy', 'man', 'sad', 'depressed', 'discouraged', 'unhappy'],
  haircut_woman: ['female', 'girl', 'woman'],
  haircut_man: ['male', 'boy', 'man'],
  massage_woman: ['female', 'girl', 'woman', 'head'],
  massage_man: ['male', 'boy', 'man', 'head'],
  woman_in_steamy_room: ['female', 'woman', 'spa', 'steamroom', 'sauna'],
  man_in_steamy_room: ['male', 'man', 'spa', 'steamroom', 'sauna'],
  couple_with_heart_woman_man: ['pair', 'love', 'like', 'affection', 'human', 'dating', 'valentines', 'marriage'],
  couple_with_heart_woman_woman: ['pair', 'love', 'like', 'affection', 'human', 'dating', 'valentines', 'marriage'],
  couple_with_heart_man_man: ['pair', 'love', 'like', 'affection', 'human', 'dating', 'valentines', 'marriage'],
  couplekiss_man_woman: ['pair', 'valentines', 'love', 'like', 'dating', 'marriage'],
  couplekiss_woman_woman: ['pair', 'valentines', 'love', 'like', 'dating', 'marriage'],
  couplekiss_man_man: ['pair', 'valentines', 'love', 'like', 'dating', 'marriage'],
  family_man_woman_boy: ['home', 'parents', 'child', 'mom', 'dad', 'father', 'mother', 'people', 'human'],
  family_man_woman_girl: ['home', 'parents', 'people', 'human', 'child'],
  family_man_woman_girl_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_man_woman_boy_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_man_woman_girl_girl: ['home', 'parents', 'people', 'human', 'children'],
  family_woman_woman_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_woman_woman_girl: ['home', 'parents', 'people', 'human', 'children'],
  family_woman_woman_girl_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_woman_woman_boy_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_woman_woman_girl_girl: ['home', 'parents', 'people', 'human', 'children'],
  family_man_man_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_man_man_girl: ['home', 'parents', 'people', 'human', 'children'],
  family_man_man_girl_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_man_man_boy_boy: ['home', 'parents', 'people', 'human', 'children'],
  family_man_man_girl_girl: ['home', 'parents', 'people', 'human', 'children'],
  family_woman_boy: ['home', 'parent', 'people', 'human', 'child'],
  family_woman_girl: ['home', 'parent', 'people', 'human', 'child'],
  family_woman_girl_boy: ['home', 'parent', 'people', 'human', 'children'],
  family_woman_boy_boy: ['home', 'parent', 'people', 'human', 'children'],
  family_woman_girl_girl: ['home', 'parent', 'people', 'human', 'children'],
  family_man_boy: ['home', 'parent', 'people', 'human', 'child'],
  family_man_girl: ['home', 'parent', 'people', 'human', 'child'],
  family_man_girl_boy: ['home', 'parent', 'people', 'human', 'children'],
  family_man_boy_boy: ['home', 'parent', 'people', 'human', 'children'],
  family_man_girl_girl: ['home', 'parent', 'people', 'human', 'children'],
  yarn: ['ball', 'crochet', 'knit'],
  thread: ['needle', 'sewing', 'spool', 'string'],
  coat: ['jacket'],
  labcoat: ['doctor', 'experiment', 'scientist', 'chemist'],
  womans_clothes: ['fashion', 'shopping_bags', 'female'],
  tshirt: ['fashion', 'cloth', 'casual', 'shirt', 'tee'],
  jeans: ['fashion', 'shopping'],
  necktie: ['shirt', 'suitup', 'formal', 'fashion', 'cloth', 'business'],
  dress: ['clothes', 'fashion', 'shopping'],
  bikini: ['swimming', 'female', 'woman', 'girl', 'fashion', 'beach', 'summer'],
  kimono: ['dress', 'fashion', 'women', 'female', 'japanese'],
  lipstick: ['female', 'girl', 'fashion', 'woman'],
  kiss: ['face', 'lips', 'love', 'like', 'affection', 'valentines'],
  footprints: ['feet', 'tracking', 'walking', 'beach'],
  flat_shoe: ['ballet', 'slip-on', 'slipper'],
  high_heel: ['fashion', 'shoes', 'female', 'pumps', 'stiletto'],
  sandal: ['shoes', 'fashion', 'flip flops'],
  boot: ['shoes', 'fashion'],
  mans_shoe: ['fashion', 'male'],
  athletic_shoe: ['shoes', 'sports', 'sneakers'],
  hiking_boot: ['backpacking', 'camping', 'hiking'],
  socks: ['stockings', 'clothes'],
  gloves: ['hands', 'winter', 'clothes'],
  scarf: ['neck', 'winter', 'clothes'],
  womans_hat: ['fashion', 'accessories', 'female', 'lady', 'spring'],
  tophat: ['magic', 'gentleman', 'classy', 'circus'],
  billed_hat: ['cap', 'baseball'],
  rescue_worker_helmet: ['construction', 'build'],
  mortar_board: [
    'school',
    'college',
    'degree',
    'university',
    'graduation',
    'cap',
    'hat',
    'legal',
    'learn',
    'education',
  ],
  crown: ['king', 'kod', 'leader', 'royalty', 'lord'],
  school_satchel: ['student', 'education', 'bag', 'backpack'],
  luggage: ['packing', 'travel'],
  pouch: ['bag', 'accessories', 'shopping'],
  purse: ['fashion', 'accessories', 'money', 'sales', 'shopping'],
  handbag: ['fashion', 'accessory', 'accessories', 'shopping'],
  briefcase: ['business', 'documents', 'work', 'law', 'legal', 'job', 'career'],
  eyeglasses: ['fashion', 'accessories', 'eyesight', 'nerdy', 'dork', 'geek'],
  dark_sunglasses: ['face', 'cool', 'accessories'],
  goggles: ['eyes', 'protection', 'safety'],
  ring: ['wedding', 'propose', 'marriage', 'valentines', 'diamond', 'fashion', 'jewelry', 'gem', 'engagement'],
  closed_umbrella: ['weather', 'rain', 'drizzle'],
  dog: ['animal', 'friend', 'nature', 'woof', 'puppy', 'pet', 'faithful'],
  cat: ['animal', 'meow', 'nature', 'pet', 'kitten'],
  mouse: ['animal', 'nature', 'cheese_wedge', 'rodent'],
  hamster: ['animal', 'nature'],
  rabbit: ['animal', 'nature', 'pet', 'spring', 'magic', 'bunny'],
  fox_face: ['animal', 'nature', 'face'],
  bear: ['animal', 'nature', 'wild'],
  panda_face: ['animal', 'nature', 'panda'],
  koala: ['animal', 'nature'],
  tiger: ['animal', 'cat', 'danger', 'wild', 'nature', 'roar'],
  lion: ['animal', 'nature'],
  cow: ['beef', 'ox', 'animal', 'nature', 'moo', 'milk'],
  pig: ['animal', 'oink', 'nature'],
  pig_nose: ['animal', 'oink'],
  frog: ['animal', 'nature', 'croak', 'toad'],
  squid: ['animal', 'nature', 'ocean', 'sea'],
  octopus: ['animal', 'creature', 'ocean', 'sea', 'nature', 'beach'],
  shrimp: ['animal', 'ocean', 'nature', 'seafood'],
  monkey_face: ['animal', 'nature', 'circus'],
  gorilla: ['animal', 'nature', 'circus'],
  see_no_evil: ['monkey', 'animal', 'nature', 'haha'],
  hear_no_evil: ['animal', 'monkey', 'nature'],
  speak_no_evil: ['monkey', 'animal', 'nature', 'omg'],
  monkey: ['animal', 'nature', 'banana', 'circus'],
  chicken: ['animal', 'cluck', 'nature', 'bird'],
  penguin: ['animal', 'nature'],
  bird: ['animal', 'nature', 'fly', 'tweet', 'spring'],
  baby_chick: ['animal', 'chicken', 'bird'],
  hatching_chick: ['animal', 'chicken', 'egg', 'born', 'baby', 'bird'],
  hatched_chick: ['animal', 'chicken', 'baby', 'bird'],
  duck: ['animal', 'nature', 'bird', 'mallard'],
  eagle: ['animal', 'nature', 'bird'],
  owl: ['animal', 'nature', 'bird', 'hoot'],
  bat: ['animal', 'nature', 'blind', 'vampire'],
  wolf: ['animal', 'nature', 'wild'],
  boar: ['animal', 'nature'],
  horse: ['animal', 'brown', 'nature'],
  unicorn: ['animal', 'nature', 'mystical'],
  honeybee: ['animal', 'insect', 'nature', 'bug', 'spring', 'honey'],
  bug: ['animal', 'insect', 'nature', 'worm'],
  butterfly: ['animal', 'insect', 'nature', 'caterpillar'],
  snail: ['slow', 'animal', 'shell'],
  beetle: ['animal', 'insect', 'nature', 'ladybug'],
  ant: ['animal', 'insect', 'nature', 'bug'],
  grasshopper: ['animal', 'cricket', 'chirp'],
  spider: ['animal', 'arachnid'],
  scorpion: ['animal', 'arachnid'],
  crab: ['animal', 'crustacean'],
  snake: ['animal', 'evil', 'nature', 'hiss', 'python'],
  lizard: ['animal', 'nature', 'reptile'],
  't-rex': ['animal', 'nature', 'dinosaur', 'tyrannosaurus', 'extinct'],
  sauropod: ['animal', 'nature', 'dinosaur', 'brachiosaurus', 'brontosaurus', 'diplodocus', 'extinct'],
  turtle: ['animal', 'slow', 'nature', 'tortoise'],
  tropical_fish: ['animal', 'swim', 'ocean', 'beach', 'nemo'],
  fish: ['animal', 'food', 'nature'],
  blowfish: ['animal', 'nature', 'food', 'sea', 'ocean'],
  dolphin: ['animal', 'nature', 'fish', 'sea', 'ocean', 'flipper', 'fins', 'beach'],
  shark: ['animal', 'nature', 'fish', 'sea', 'ocean', 'jaws', 'fins', 'beach'],
  whale: ['animal', 'nature', 'sea', 'ocean'],
  whale2: ['animal', 'nature', 'sea', 'ocean'],
  crocodile: ['animal', 'nature', 'reptile', 'lizard', 'alligator'],
  leopard: ['animal', 'nature'],
  zebra: ['animal', 'nature', 'stripes', 'safari'],
  tiger2: ['animal', 'nature', 'roar'],
  water_buffalo: ['animal', 'nature', 'ox', 'cow'],
  ox: ['animal', 'cow', 'beef'],
  cow2: ['beef', 'ox', 'animal', 'nature', 'moo', 'milk'],
  deer: ['animal', 'nature', 'horns', 'venison'],
  dromedary_camel: ['animal', 'hot', 'desert', 'hump'],
  camel: ['animal', 'nature', 'hot', 'desert', 'hump'],
  giraffe: ['animal', 'nature', 'spots', 'safari'],
  elephant: ['animal', 'nature', 'nose', 'th', 'circus'],
  rhinoceros: ['animal', 'nature', 'horn'],
  goat: ['animal', 'nature'],
  ram: ['animal', 'sheep', 'nature'],
  sheep: ['animal', 'nature', 'wool', 'shipit'],
  racehorse: ['animal', 'gamble', 'luck'],
  pig2: ['animal', 'nature'],
  rat: ['animal', 'mouse', 'rodent'],
  mouse2: ['animal', 'nature', 'rodent'],
  rooster: ['animal', 'nature', 'chicken'],
  turkey: ['animal', 'bird'],
  dove: ['animal', 'bird'],
  dog2: ['animal', 'nature', 'friend', 'doge', 'pet', 'faithful'],
  poodle: ['dog', 'animal', '101', 'nature', 'pet'],
  cat2: ['animal', 'meow', 'pet', 'cats'],
  rabbit2: ['animal', 'nature', 'pet', 'magic', 'spring'],
  chipmunk: ['animal', 'nature', 'rodent', 'squirrel'],
  hedgehog: ['animal', 'nature', 'spiny'],
  raccoon: ['animal', 'nature'],
  llama: ['animal', 'nature', 'alpaca'],
  hippopotamus: ['animal', 'nature'],
  kangaroo: ['animal', 'nature', 'australia', 'joey', 'hop', 'marsupial'],
  badger: ['animal', 'nature', 'honey'],
  swan: ['animal', 'nature', 'bird'],
  peacock: ['animal', 'nature', 'peahen', 'bird'],
  parrot: ['animal', 'nature', 'bird', 'pirate', 'talk'],
  lobster: ['animal', 'nature', 'bisque', 'claws', 'seafood'],
  mosquito: ['animal', 'nature', 'insect', 'malaria'],
  paw_prints: ['animal', 'tracking', 'footprints', 'dog', 'cat', 'pet', 'feet'],
  dragon: ['animal', 'myth', 'nature', 'chinese', 'green'],
  dragon_face: ['animal', 'myth', 'nature', 'chinese', 'green'],
  cactus: ['vegetable', 'plant', 'nature'],
  christmas_tree: ['festival', 'vacation', 'december', 'xmas', 'celebration'],
  evergreen_tree: ['plant', 'nature'],
  deciduous_tree: ['plant', 'nature'],
  palm_tree: ['plant', 'vegetable', 'nature', 'summer', 'beach', 'mojito', 'tropical'],
  seedling: ['plant', 'nature', 'grass', 'lawn', 'spring'],
  herb: ['vegetable', 'plant', 'medicine', 'weed', 'grass', 'lawn'],
  shamrock: ['vegetable', 'plant', 'nature', 'irish', 'clover'],
  four_leaf_clover: ['vegetable', 'plant', 'nature', 'lucky', 'irish'],
  bamboo: ['plant', 'nature', 'vegetable', 'panda', 'pine_decoration'],
  tanabata_tree: ['plant', 'nature', 'branch', 'summer'],
  leaves: ['nature', 'plant', 'tree', 'vegetable', 'grass', 'lawn', 'spring'],
  fallen_leaf: ['nature', 'plant', 'vegetable', 'leaves'],
  maple_leaf: ['nature', 'plant', 'vegetable', 'ca', 'fall'],
  ear_of_rice: ['nature', 'plant'],
  hibiscus: ['plant', 'vegetable', 'flowers', 'beach'],
  sunflower: ['nature', 'plant', 'fall'],
  rose: ['flowers', 'valentines', 'love', 'spring'],
  wilted_flower: ['plant', 'nature', 'flower'],
  tulip: ['flowers', 'plant', 'nature', 'summer', 'spring'],
  blossom: ['nature', 'flowers', 'yellow'],
  cherry_blossom: ['nature', 'plant', 'spring', 'flower'],
  bouquet: ['flowers', 'nature', 'spring'],
  mushroom: ['plant', 'vegetable'],
  chestnut: ['food', 'squirrel'],
  jack_o_lantern: ['halloween', 'light', 'pumpkin', 'creepy', 'fall'],
  shell: ['nature', 'sea', 'beach'],
  spider_web: ['animal', 'insect', 'arachnid', 'silk'],
  earth_americas: ['globe', 'world', 'USA', 'international'],
  earth_africa: ['globe', 'world', 'international'],
  earth_asia: ['globe', 'world', 'east', 'international'],
  full_moon: ['nature', 'yellow', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  waning_gibbous_moon: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep', 'waxing_gibbous_moon'],
  last_quarter_moon: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  waning_crescent_moon: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  new_moon: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  waxing_crescent_moon: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  first_quarter_moon: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  waxing_gibbous_moon: ['nature', 'night', 'sky', 'gray', 'twilight', 'planet', 'space', 'evening', 'sleep'],
  new_moon_with_face: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  full_moon_with_face: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  first_quarter_moon_with_face: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  last_quarter_moon_with_face: ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
  sun_with_face: ['nature', 'morning', 'sky'],
  crescent_moon: ['night', 'sleep', 'sky', 'evening', 'magic'],
  star: ['night', 'yellow'],
  star2: ['night', 'sparkle', 'awesome', 'good', 'magic'],
  dizzy: ['star', 'sparkle', 'shoot', 'magic'],
  sparkles: ['stars', 'shine', 'shiny', 'cool', 'awesome', 'good', 'magic'],
  comet: ['space'],
  sunny: ['weather', 'nature', 'brightness', 'summer', 'beach', 'spring'],
  sun_behind_small_cloud: ['weather'],
  partly_sunny: ['weather', 'nature', 'cloudy', 'morning', 'fall', 'spring'],
  sun_behind_large_cloud: ['weather'],
  sun_behind_rain_cloud: ['weather'],
  cloud: ['weather', 'sky'],
  cloud_with_rain: ['weather'],
  cloud_with_lightning_and_rain: ['weather', 'lightning'],
  cloud_with_lightning: ['weather', 'thunder'],
  zap: ['thunder', 'weather', 'lightning bolt', 'fast'],
  fire: ['hot', 'cook', 'flame'],
  boom: ['bomb', 'explode', 'explosion', 'collision', 'blown'],
  snowflake: ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas'],
  cloud_with_snow: ['weather'],
  snowman: ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas', 'frozen', 'without_snow'],
  snowman_with_snow: ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas', 'frozen'],
  wind_face: ['gust', 'air'],
  dash: ['wind', 'air', 'fast', 'shoo', 'fart', 'smoke', 'puff'],
  tornado: ['weather', 'cyclone', 'twister'],
  fog: ['weather'],
  open_umbrella: ['weather', 'spring'],
  umbrella: ['rainy', 'weather', 'spring'],
  droplet: ['water', 'drip', 'faucet', 'spring'],
  sweat_drops: ['water', 'drip', 'oops'],
  ocean: ['sea', 'water', 'wave', 'nature', 'tsunami', 'disaster'],
  green_apple: ['fruit', 'nature'],
  apple: ['fruit', 'mac', 'school'],
  pear: ['fruit', 'nature', 'food'],
  tangerine: ['food', 'fruit', 'nature', 'orange'],
  lemon: ['fruit', 'nature'],
  banana: ['fruit', 'food', 'monkey'],
  watermelon: ['fruit', 'food', 'picnic', 'summer'],
  grapes: ['fruit', 'food', 'wine'],
  strawberry: ['fruit', 'food', 'nature'],
  melon: ['fruit', 'nature', 'food'],
  cherries: ['food', 'fruit'],
  peach: ['fruit', 'nature', 'food'],
  pineapple: ['fruit', 'nature', 'food'],
  coconut: ['fruit', 'nature', 'food', 'palm'],
  kiwi_fruit: ['fruit', 'food'],
  mango: ['fruit', 'food', 'tropical'],
  avocado: ['fruit', 'food'],
  broccoli: ['fruit', 'food', 'vegetable'],
  tomato: ['fruit', 'vegetable', 'nature', 'food'],
  eggplant: ['vegetable', 'nature', 'food', 'aubergine'],
  cucumber: ['fruit', 'food', 'pickle'],
  carrot: ['vegetable', 'food', 'orange'],
  hot_pepper: ['food', 'spicy', 'chilli', 'chili'],
  potato: ['food', 'tuber', 'vegatable', 'starch'],
  corn: ['food', 'vegetable', 'plant'],
  leafy_greens: ['food', 'vegetable', 'plant', 'bok choy', 'cabbage', 'kale', 'lettuce'],
  sweet_potato: ['food', 'nature'],
  peanuts: ['food', 'nut'],
  honey_pot: ['bees', 'sweet', 'kitchen'],
  croissant: ['food', 'bread', 'french'],
  bread: ['food', 'wheat', 'breakfast', 'toast'],
  baguette_bread: ['food', 'bread', 'french'],
  bagel: ['food', 'bread', 'bakery', 'schmear'],
  pretzel: ['food', 'bread', 'twisted'],
  cheese: ['food', 'chadder'],
  egg: ['food', 'chicken', 'breakfast'],
  bacon: ['food', 'breakfast', 'pork', 'pig', 'meat'],
  steak: ['food', 'cow', 'meat', 'cut', 'chop', 'lambchop', 'porkchop'],
  pancakes: ['food', 'breakfast', 'flapjacks', 'hotcakes'],
  poultry_leg: ['food', 'meat', 'drumstick', 'bird', 'chicken', 'turkey'],
  meat_on_bone: ['good', 'food', 'drumstick'],
  bone: ['skeleton'],
  fried_shrimp: ['food', 'animal', 'appetizer', 'summer'],
  fried_egg: ['food', 'breakfast', 'kitchen', 'egg'],
  hamburger: ['meat', 'fast food', 'beef', 'cheeseburger', 'mcdonalds', 'burger king'],
  fries: ['chips', 'snack', 'fast food'],
  stuffed_flatbread: ['food', 'flatbread', 'stuffed', 'gyro'],
  hotdog: ['food', 'frankfurter'],
  pizza: ['food', 'party'],
  sandwich: ['food', 'lunch', 'bread'],
  canned_food: ['food', 'soup'],
  spaghetti: ['food', 'italian', 'noodle'],
  taco: ['food', 'mexican'],
  burrito: ['food', 'mexican'],
  green_salad: ['food', 'healthy', 'lettuce'],
  shallow_pan_of_food: ['food', 'cooking', 'casserole', 'paella'],
  ramen: ['food', 'japanese', 'noodle', 'chopsticks'],
  stew: ['food', 'meat', 'soup'],
  fish_cake: ['food', 'japan', 'sea', 'beach', 'narutomaki', 'pink', 'swirl', 'kamaboko', 'surimi', 'ramen'],
  fortune_cookie: ['food', 'prophecy'],
  sushi: ['food', 'fish', 'japanese', 'rice'],
  bento: ['food', 'japanese', 'box'],
  curry: ['food', 'spicy', 'hot', 'indian'],
  rice_ball: ['food', 'japanese'],
  rice: ['food', 'china', 'asian'],
  rice_cracker: ['food', 'japanese'],
  oden: ['food', 'japanese'],
  dango: ['food', 'dessert', 'sweet', 'japanese', 'barbecue', 'meat'],
  shaved_ice: ['hot', 'dessert', 'summer'],
  ice_cream: ['food', 'hot', 'dessert'],
  icecream: ['food', 'hot', 'dessert', 'summer'],
  pie: ['food', 'dessert', 'pastry'],
  cake: ['food', 'dessert'],
  cupcake: ['food', 'dessert', 'bakery', 'sweet'],
  moon_cake: ['food', 'autumn'],
  birthday: ['food', 'dessert', 'cake'],
  custard: ['dessert', 'food'],
  candy: ['snack', 'dessert', 'sweet', 'lolly'],
  lollipop: ['food', 'snack', 'candy', 'sweet'],
  chocolate_bar: ['food', 'snack', 'dessert', 'sweet'],
  popcorn: ['food', 'movie theater', 'films', 'snack'],
  dumpling: ['food', 'empanada', 'pierogi', 'potsticker'],
  doughnut: ['food', 'dessert', 'snack', 'sweet', 'donut'],
  cookie: ['food', 'snack', 'oreo', 'chocolate', 'sweet', 'dessert'],
  milk_glass: ['beverage', 'drink', 'cow'],
  beer: ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze'],
  beers: ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze'],
  clinking_glasses: ['beverage', 'drink', 'party', 'alcohol', 'celebrate', 'cheers', 'wine', 'champagne', 'toast'],
  wine_glass: ['drink', 'beverage', 'drunk', 'alcohol', 'booze'],
  tumbler_glass: [
    'drink',
    'beverage',
    'drunk',
    'alcohol',
    'liquor',
    'booze',
    'bourbon',
    'scotch',
    'whisky',
    'glass',
    'shot',
  ],
  cocktail: ['drink', 'drunk', 'alcohol', 'beverage', 'booze', 'mojito'],
  tropical_drink: ['beverage', 'cocktail', 'summer', 'beach', 'alcohol', 'booze', 'mojito'],
  champagne: ['drink', 'wine', 'bottle', 'celebration'],
  sake: ['wine', 'drink', 'drunk', 'beverage', 'japanese', 'alcohol', 'booze'],
  tea: ['drink', 'bowl', 'breakfast', 'green', 'british'],
  cup_with_straw: ['drink', 'soda'],
  coffee: ['beverage', 'caffeine', 'latte', 'espresso'],
  baby_bottle: ['food', 'container', 'milk'],
  salt: ['condiment', 'shaker'],
  spoon: ['cutlery', 'kitchen', 'tableware'],
  fork_and_knife: ['cutlery', 'kitchen'],
  plate_with_cutlery: ['food', 'eat', 'meal', 'lunch', 'dinner', 'restaurant'],
  bowl_with_spoon: ['food', 'breakfast', 'cereal', 'oatmeal', 'porridge'],
  takeout_box: ['food', 'leftovers'],
  chopsticks: ['food'],
  soccer: ['sports', 'football'],
  basketball: ['sports', 'balls', 'NBA'],
  football: ['sports', 'balls', 'NFL'],
  baseball: ['sports', 'balls'],
  softball: ['sports', 'balls'],
  tennis: ['sports', 'balls', 'green'],
  volleyball: ['sports', 'balls'],
  rugby_football: ['sports', 'team'],
  flying_disc: ['sports', 'frisbee', 'ultimate'],
  '8ball': ['pool', 'hobby', 'game', 'luck', 'magic'],
  golf: ['sports', 'business', 'flag', 'hole', 'summer'],
  golfing_woman: ['sports', 'business', 'woman', 'female'],
  golfing_man: ['sports', 'business'],
  ping_pong: ['sports', 'pingpong'],
  badminton: ['sports'],
  goal_net: ['sports'],
  ice_hockey: ['sports'],
  field_hockey: ['sports'],
  lacrosse: ['sports', 'ball', 'stick'],
  cricket: ['sports'],
  ski: ['sports', 'winter', 'cold', 'snow'],
  skier: ['sports', 'winter', 'snow'],
  snowboarder: ['sports', 'winter'],
  person_fencing: ['sports', 'fencing', 'sword'],
  women_wrestling: ['sports', 'wrestlers'],
  men_wrestling: ['sports', 'wrestlers'],
  woman_cartwheeling: ['gymnastics'],
  man_cartwheeling: ['gymnastics'],
  woman_playing_handball: ['sports'],
  man_playing_handball: ['sports'],
  ice_skate: ['sports'],
  curling_stone: ['sports'],
  skateboard: ['board'],
  sled: ['sleigh', 'luge', 'toboggan'],
  bow_and_arrow: ['sports'],
  fishing_pole_and_fish: ['food', 'hobby', 'summer'],
  boxing_glove: ['sports', 'fighting'],
  martial_arts_uniform: ['judo', 'karate', 'taekwondo'],
  rowing_woman: ['sports', 'hobby', 'water', 'ship', 'woman', 'female'],
  rowing_man: ['sports', 'hobby', 'water', 'ship'],
  climbing_woman: ['sports', 'hobby', 'woman', 'female', 'rock'],
  climbing_man: ['sports', 'hobby', 'man', 'male', 'rock'],
  swimming_woman: ['sports', 'exercise', 'human', 'athlete', 'water', 'summer', 'woman', 'female'],
  swimming_man: ['sports', 'exercise', 'human', 'athlete', 'water', 'summer'],
  woman_playing_water_polo: ['sports', 'pool'],
  man_playing_water_polo: ['sports', 'pool'],
  woman_in_lotus_position: ['woman', 'female', 'meditation', 'yoga', 'serenity', 'zen', 'mindfulness'],
  man_in_lotus_position: ['man', 'male', 'meditation', 'yoga', 'serenity', 'zen', 'mindfulness'],
  surfing_woman: ['sports', 'ocean', 'sea', 'summer', 'beach', 'woman', 'female'],
  surfing_man: ['sports', 'ocean', 'sea', 'summer', 'beach'],
  bath: ['clean', 'shower', 'bathroom'],
  basketball_woman: ['sports', 'human', 'woman', 'female'],
  basketball_man: ['sports', 'human'],
  weight_lifting_woman: ['sports', 'training', 'exercise', 'woman', 'female'],
  weight_lifting_man: ['sports', 'training', 'exercise'],
  biking_woman: ['sports', 'bike', 'exercise', 'hipster', 'woman', 'female'],
  biking_man: ['sports', 'bike', 'exercise', 'hipster'],
  mountain_biking_woman: ['transportation', 'sports', 'human', 'race', 'bike', 'woman', 'female'],
  mountain_biking_man: ['transportation', 'sports', 'human', 'race', 'bike'],
  horse_racing: ['animal', 'betting', 'competition', 'gambling', 'luck'],
  business_suit_levitating: ['suit', 'business', 'levitate', 'hover', 'jump'],
  trophy: ['win', 'award', 'contest', 'place', 'ftw', 'ceremony'],
  running_shirt_with_sash: ['play', 'pageant'],
  medal_sports: ['award', 'winning'],
  medal_military: ['award', 'winning', 'army'],
  '1st_place_medal': ['award', 'winning', 'first'],
  '2nd_place_medal': ['award', 'second'],
  '3rd_place_medal': ['award', 'third'],
  reminder_ribbon: ['sports', 'cause', 'support', 'awareness'],
  rosette: ['flower', 'decoration', 'military'],
  ticket: ['event', 'concert', 'pass'],
  tickets: ['sports', 'concert', 'entrance'],
  performing_arts: ['acting', 'theater', 'drama'],
  art: ['design', 'paint', 'draw', 'colors'],
  circus_tent: ['festival', 'carnival', 'party'],
  woman_juggling: ['juggle', 'balance', 'skill', 'multitask'],
  man_juggling: ['juggle', 'balance', 'skill', 'multitask'],
  microphone: ['sound', 'music', 'PA', 'sing', 'talkshow'],
  headphones: ['music', 'score', 'gadgets'],
  musical_score: ['treble', 'clef', 'compose'],
  musical_keyboard: ['piano', 'instrument', 'compose'],
  drum: ['music', 'instrument', 'drumsticks', 'snare'],
  saxophone: ['music', 'instrument', 'jazz', 'blues'],
  trumpet: ['music', 'brass'],
  guitar: ['music', 'instrument'],
  violin: ['music', 'instrument', 'orchestra', 'symphony'],
  clapper: ['movie', 'film', 'record'],
  video_game: ['play', 'console', 'PS4', 'controller'],
  space_invader: ['game', 'arcade', 'play'],
  dart: ['game', 'play', 'bar', 'target', 'bullseye'],
  game_die: ['dice', 'random', 'tabletop', 'play', 'luck'],
  chess_pawn: ['expendable'],
  slot_machine: ['bet', 'gamble', 'vegas', 'fruit machine', 'luck', 'casino'],
  jigsaw: ['interlocking', 'puzzle', 'piece'],
  bowling: ['sports', 'fun', 'play'],
  red_car: ['red', 'transportation', 'vehicle'],
  taxi: ['uber', 'vehicle', 'cars', 'transportation'],
  blue_car: ['transportation', 'vehicle'],
  bus: ['car', 'vehicle', 'transportation'],
  trolleybus: ['bart', 'transportation', 'vehicle'],
  racing_car: ['sports', 'race', 'fast', 'formula', 'f1'],
  police_car: ['vehicle', 'cars', 'transportation', 'law', 'legal', 'enforcement'],
  ambulance: ['health', '911', 'hospital'],
  fire_engine: ['transportation', 'cars', 'vehicle'],
  minibus: ['vehicle', 'car', 'transportation'],
  truck: ['cars', 'transportation'],
  articulated_lorry: ['vehicle', 'cars', 'transportation', 'express'],
  tractor: ['vehicle', 'car', 'farming', 'agriculture'],
  kick_scooter: ['vehicle', 'kick', 'razor'],
  motorcycle: ['race', 'sports', 'fast'],
  bike: ['sports', 'bicycle', 'exercise', 'hipster'],
  motor_scooter: ['vehicle', 'vespa', 'sasha'],
  rotating_light: ['police', 'ambulance', '911', 'emergency', 'alert', 'error', 'pinged', 'law', 'legal'],
  oncoming_police_car: ['vehicle', 'law', 'legal', 'enforcement', '911'],
  oncoming_bus: ['vehicle', 'transportation'],
  oncoming_automobile: ['car', 'vehicle', 'transportation'],
  oncoming_taxi: ['vehicle', 'cars', 'uber'],
  aerial_tramway: ['transportation', 'vehicle', 'ski'],
  mountain_cableway: ['transportation', 'vehicle', 'ski'],
  suspension_railway: ['vehicle', 'transportation'],
  railway_car: ['transportation', 'vehicle'],
  train: ['transportation', 'vehicle', 'carriage', 'public', 'travel'],
  monorail: ['transportation', 'vehicle'],
  bullettrain_side: ['transportation', 'vehicle'],
  bullettrain_front: ['transportation', 'vehicle', 'speed', 'fast', 'public', 'travel'],
  light_rail: ['transportation', 'vehicle'],
  mountain_railway: ['transportation', 'vehicle'],
  steam_locomotive: ['transportation', 'vehicle', 'train'],
  train2: ['transportation', 'vehicle'],
  metro: ['transportation', 'blue-square', 'mrt', 'underground', 'tube'],
  tram: ['transportation', 'vehicle'],
  station: ['transportation', 'vehicle', 'public'],
  flying_saucer: ['transportation', 'vehicle', 'ufo'],
  helicopter: ['transportation', 'vehicle', 'fly'],
  small_airplane: ['flight', 'transportation', 'fly', 'vehicle'],
  airplane: ['vehicle', 'transportation', 'flight', 'fly'],
  flight_departure: ['airport', 'flight', 'landing'],
  flight_arrival: ['airport', 'flight', 'boarding'],
  sailboat: ['ship', 'summer', 'transportation', 'water', 'sailing'],
  motor_boat: ['ship'],
  speedboat: ['ship', 'transportation', 'vehicle', 'summer'],
  ferry: ['boat', 'ship', 'yacht'],
  passenger_ship: ['yacht', 'cruise', 'ferry'],
  rocket: ['launch', 'ship', 'staffmode', 'NASA', 'outer space', 'outer_space', 'fly'],
  artificial_satellite: ['communication', 'gps', 'orbit', 'spaceflight', 'NASA', 'ISS'],
  seat: ['sit', 'airplane', 'transport', 'bus', 'flight', 'fly'],
  canoe: ['boat', 'paddle', 'water', 'ship'],
  anchor: ['ship', 'ferry', 'sea', 'boat'],
  construction: ['wip', 'progress', 'caution', 'warning'],
  fuelpump: ['gas station', 'petroleum'],
  busstop: ['transportation', 'wait'],
  vertical_traffic_light: ['transportation', 'driving'],
  traffic_light: ['transportation', 'signal'],
  checkered_flag: ['contest', 'finishline', 'race', 'gokart'],
  ship: ['transportation', 'titanic', 'deploy'],
  ferris_wheel: ['photo', 'carnival', 'londoneye'],
  roller_coaster: ['carnival', 'playground', 'photo', 'fun'],
  carousel_horse: ['photo', 'carnival'],
  building_construction: ['wip', 'working', 'progress'],
  foggy: ['photo', 'mountain'],
  tokyo_tower: ['photo', 'japanese'],
  factory: ['building', 'industry', 'pollution', 'smoke'],
  fountain: ['photo', 'summer', 'water', 'fresh'],
  rice_scene: ['photo', 'japan', 'asia', 'tsukimi'],
  mountain: ['photo', 'nature', 'environment'],
  mountain_snow: ['photo', 'nature', 'environment', 'winter', 'cold'],
  mount_fuji: ['photo', 'mountain', 'nature', 'japanese'],
  volcano: ['photo', 'nature', 'disaster'],
  japan: ['nation', 'country', 'japanese', 'asia'],
  camping: ['photo', 'outdoors', 'tent'],
  tent: ['photo', 'camping', 'outdoors'],
  national_park: ['photo', 'environment', 'nature'],
  motorway: ['road', 'cupertino', 'interstate', 'highway'],
  railway_track: ['train', 'transportation'],
  sunrise: ['morning', 'view', 'vacation', 'photo'],
  sunrise_over_mountains: ['view', 'vacation', 'photo'],
  desert: ['photo', 'warm', 'saharah'],
  beach_umbrella: ['weather', 'summer', 'sunny', 'sand', 'mojito'],
  desert_island: ['photo', 'tropical', 'mojito'],
  city_sunrise: ['photo', 'good morning', 'dawn'],
  city_sunset: ['photo', 'evening', 'sky', 'buildings'],
  cityscape: ['photo', 'night life', 'urban'],
  night_with_stars: ['evening', 'city', 'downtown'],
  bridge_at_night: ['photo', 'sanfrancisco'],
  milky_way: ['photo', 'space', 'stars'],
  stars: ['night', 'photo'],
  sparkler: ['stars', 'night', 'shine'],
  fireworks: ['photo', 'festival', 'carnival', 'congratulations'],
  rainbow: ['nature', 'happy', 'unicorn_face', 'photo', 'sky', 'spring'],
  houses: ['buildings', 'photo'],
  european_castle: ['building', 'royalty', 'history'],
  japanese_castle: ['photo', 'building'],
  stadium: ['photo', 'place', 'sports', 'concert', 'venue'],
  statue_of_liberty: ['american', 'newyork'],
  house: ['building', 'home'],
  house_with_garden: ['home', 'plant', 'nature'],
  derelict_house: ['abandon', 'evict', 'broken', 'building'],
  office: ['building', 'bureau', 'work'],
  department_store: ['building', 'shopping', 'mall'],
  post_office: ['building', 'envelope', 'communication'],
  european_post_office: ['building', 'email'],
  hospital: ['building', 'health', 'surgery', 'doctor'],
  bank: ['building', 'money', 'sales', 'cash', 'business', 'enterprise'],
  hotel: ['building', 'accomodation', 'checkin'],
  convenience_store: ['building', 'shopping', 'groceries'],
  school: ['building', 'student', 'education', 'learn', 'teach'],
  love_hotel: ['like', 'affection', 'dating'],
  wedding: ['love', 'like', 'affection', 'couple', 'marriage', 'bride', 'groom'],
  classical_building: ['art', 'culture', 'history'],
  church: ['building', 'religion', 'christ'],
  mosque: ['islam', 'worship', 'minaret'],
  synagogue: ['judaism', 'worship', 'temple', 'jewish'],
  kaaba: ['mecca', 'mosque', 'islam'],
  shinto_shrine: ['temple', 'japan', 'kyoto'],
  watch: ['time', 'accessories'],
  iphone: ['technology', 'apple', 'gadgets', 'dial'],
  calling: ['iphone', 'incoming'],
  computer: ['technology', 'laptop', 'screen', 'display', 'monitor'],
  keyboard: ['technology', 'computer', 'type', 'input', 'text'],
  desktop_computer: ['technology', 'computing', 'screen'],
  printer: ['paper', 'ink'],
  computer_mouse: ['click'],
  trackball: ['technology', 'trackpad'],
  joystick: ['game', 'play'],
  clamp: ['tool'],
  minidisc: ['technology', 'record', 'data', 'disk', '90s'],
  floppy_disk: ['oldschool', 'technology', 'save', '90s', '80s'],
  cd: ['technology', 'dvd', 'disk', 'disc', '90s'],
  dvd: ['cd', 'disk', 'disc'],
  vhs: ['record', 'video', 'oldschool', '90s', '80s'],
  camera: ['gadgets', 'photography'],
  camera_flash: ['photography', 'gadgets'],
  video_camera: ['film', 'record'],
  movie_camera: ['film', 'record'],
  film_projector: ['video', 'tape', 'record', 'movie'],
  film_strip: ['movie'],
  telephone_receiver: ['technology', 'communication', 'dial'],
  phone: ['technology', 'communication', 'dial', 'telephone'],
  pager: ['bbcall', 'oldschool', '90s'],
  fax: ['communication', 'technology'],
  tv: ['technology', 'program', 'oldschool', 'show', 'television'],
  radio: ['communication', 'music', 'podcast', 'program'],
  studio_microphone: ['sing', 'recording', 'artist', 'talkshow'],
  level_slider: ['scale'],
  control_knobs: ['dial'],
  compass: ['magnetic', 'navigation', 'orienteering'],
  stopwatch: ['time', 'deadline'],
  timer_clock: ['alarm'],
  alarm_clock: ['time', 'wake'],
  mantelpiece_clock: ['time'],
  hourglass_flowing_sand: ['oldschool', 'time', 'countdown'],
  hourglass: ['time', 'clock', 'oldschool', 'limit', 'exam', 'quiz', 'test'],
  satellite: ['communication', 'future', 'radio', 'space'],
  battery: ['power', 'energy', 'sustain'],
  electric_plug: ['charger', 'power'],
  bulb: ['light', 'electricity', 'idea'],
  flashlight: ['dark', 'camping', 'sight', 'night'],
  candle: ['fire', 'wax'],
  fire_extinguisher: ['quench'],
  wastebasket: ['bin', 'trash', 'rubbish', 'garbage', 'toss'],
  oil_drum: ['barrell'],
  money_with_wings: ['dollar', 'bills', 'payment', 'sale'],
  dollar: ['money', 'sales', 'bill', 'currency'],
  yen: ['money', 'sales', 'japanese', 'dollar', 'currency'],
  euro: ['money', 'sales', 'dollar', 'currency'],
  pound: ['british', 'sterling', 'money', 'sales', 'bills', 'uk', 'england', 'currency'],
  moneybag: ['dollar', 'payment', 'coins', 'sale'],
  credit_card: ['money', 'sales', 'dollar', 'bill', 'payment', 'shopping'],
  gem: ['blue', 'ruby', 'diamond', 'jewelry'],
  balance_scale: ['law', 'fairness', 'weight'],
  toolbox: ['tools', 'diy', 'fix', 'maintainer', 'mechanic'],
  wrench: ['tools', 'diy', 'ikea', 'fix', 'maintainer'],
  hammer: ['tools', 'build', 'create'],
  hammer_and_pick: ['tools', 'build', 'create'],
  hammer_and_wrench: ['tools', 'build', 'create'],
  pick: ['tools', 'dig'],
  nut_and_bolt: ['handy', 'tools', 'fix'],
  gear: ['cog'],
  brick: ['bricks'],
  chains: ['lock', 'arrest'],
  magnet: ['attraction', 'magnetic'],
  gun: ['violence', 'weapon', 'pistol', 'revolver'],
  bomb: ['boom', 'explode', 'explosion', 'terrorism'],
  firecracker: ['dynamite', 'boom', 'explode', 'explosion', 'explosive'],
  hocho: ['knife', 'blade', 'cutlery', 'kitchen', 'weapon'],
  dagger: ['weapon'],
  crossed_swords: ['weapon'],
  shield: ['protection', 'security'],
  smoking: ['kills', 'tobacco', 'cigarette', 'joint', 'smoke'],
  skull_and_crossbones: ['poison', 'danger', 'deadly', 'scary', 'death', 'pirate', 'evil'],
  coffin: ['vampire', 'dead', 'die', 'death', 'rip', 'graveyard', 'cemetery', 'casket', 'funeral', 'box'],
  funeral_urn: ['dead', 'die', 'death', 'rip', 'ashes'],
  amphora: ['vase', 'jar'],
  crystal_ball: ['disco', 'party', 'magic', 'circus', 'fortune_teller'],
  prayer_beads: ['dhikr', 'religious'],
  nazar_amulet: ['bead', 'charm'],
  barber: ['hair', 'salon', 'style'],
  alembic: ['distilling', 'science', 'experiment', 'chemistry'],
  telescope: ['stars', 'space', 'zoom', 'science', 'astronomy'],
  microscope: ['laboratory', 'experiment', 'zoomin', 'science', 'study'],
  hole: ['embarrassing'],
  pill: ['health', 'medicine', 'doctor', 'pharmacy', 'drug'],
  syringe: ['health', 'hospital', 'drugs', 'blood', 'medicine', 'needle', 'doctor', 'nurse'],
  dna: ['biologist', 'genetics', 'life'],
  microbe: ['amoeba', 'bacteria', 'germs'],
  petri_dish: ['bacteria', 'biology', 'culture', 'lab'],
  test_tube: ['chemistry', 'experiment', 'lab', 'science'],
  thermometer: ['weather', 'temperature', 'hot', 'cold'],
  broom: ['cleaning', 'sweeping', 'witch'],
  basket: ['laundry'],
  toilet_paper: ['roll'],
  label: ['sale', 'tag'],
  bookmark: ['favorite', 'label', 'save'],
  toilet: ['restroom', 'wc', 'washroom', 'bathroom', 'potty'],
  shower: ['clean', 'water', 'bathroom'],
  bathtub: ['clean', 'shower', 'bathroom'],
  soap: ['bar', 'bathing', 'cleaning', 'lather'],
  sponge: ['absorbing', 'cleaning', 'porous'],
  lotion_bottle: ['moisturizer', 'sunscreen'],
  key: ['lock', 'door', 'password'],
  old_key: ['lock', 'door', 'password'],
  couch_and_lamp: ['read', 'chill'],
  sleeping_bed: ['bed', 'rest'],
  bed: ['sleep', 'rest'],
  door: ['house', 'entry', 'exit'],
  bellhop_bell: ['service'],
  teddy_bear: ['plush', 'stuffed'],
  framed_picture: ['photography'],
  world_map: ['location', 'direction'],
  parasol_on_ground: ['weather', 'summer'],
  moyai: ['rock', 'easter island', 'moai'],
  shopping: ['mall', 'buy', 'purchase'],
  shopping_cart: ['trolley'],
  balloon: ['party', 'celebration', 'birthday', 'circus'],
  flags: ['fish', 'japanese', 'koinobori', 'carp', 'banner'],
  ribbon: ['decoration', 'pink', 'girl', 'bowtie'],
  gift: ['present', 'birthday', 'christmas', 'xmas'],
  confetti_ball: ['festival', 'party', 'birthday', 'circus'],
  tada: ['party', 'congratulations', 'birthday', 'magic', 'circus', 'celebration'],
  dolls: ['japanese', 'toy', 'kimono'],
  wind_chime: ['nature', 'ding', 'spring', 'bell'],
  crossed_flags: ['japanese', 'nation', 'country', 'border'],
  izakaya_lantern: ['light', 'paper', 'halloween', 'spooky'],
  red_envelope: ['gift'],
  email: ['letter', 'postal', 'inbox', 'communication'],
  envelope_with_arrow: ['email', 'communication'],
  incoming_envelope: ['email', 'inbox'],
  'e-mail': ['communication', 'inbox'],
  love_letter: ['email', 'like', 'affection', 'envelope', 'valentines'],
  postbox: ['email', 'letter', 'envelope'],
  mailbox_closed: ['email', 'communication', 'inbox'],
  mailbox: ['email', 'inbox', 'communication'],
  mailbox_with_mail: ['email', 'inbox', 'communication'],
  mailbox_with_no_mail: ['email', 'inbox'],
  package: ['mail', 'gift', 'cardboard', 'box', 'moving'],
  postal_horn: ['instrument', 'music'],
  inbox_tray: ['email', 'documents'],
  outbox_tray: ['inbox', 'email'],
  scroll: ['documents', 'ancient', 'history', 'paper'],
  page_with_curl: ['documents', 'office', 'paper'],
  bookmark_tabs: ['favorite', 'save', 'order', 'tidy'],
  receipt: ['accounting', 'expenses'],
  bar_chart: ['graph', 'presentation', 'stats'],
  chart_with_upwards_trend: [
    'graph',
    'presentation',
    'stats',
    'recovery',
    'business',
    'economics',
    'money',
    'sales',
    'good',
    'success',
  ],
  chart_with_downwards_trend: [
    'graph',
    'presentation',
    'stats',
    'recession',
    'business',
    'economics',
    'money',
    'sales',
    'bad',
    'failure',
  ],
  page_facing_up: ['documents', 'office', 'paper', 'information'],
  date: ['calendar', 'schedule'],
  calendar: ['schedule', 'date', 'planning'],
  spiral_calendar: ['date', 'schedule', 'planning'],
  card_index: ['business', 'stationery'],
  card_file_box: ['business', 'stationery'],
  ballot_box: ['election', 'vote'],
  file_cabinet: ['filing', 'organizing'],
  clipboard: ['stationery', 'documents'],
  spiral_notepad: ['memo', 'stationery'],
  file_folder: ['documents', 'business', 'office'],
  open_file_folder: ['documents', 'load'],
  card_index_dividers: ['organizing', 'business', 'stationery'],
  newspaper_roll: ['press', 'headline'],
  newspaper: ['press', 'headline'],
  notebook: ['stationery', 'record', 'notes', 'paper', 'study'],
  closed_book: ['read', 'library', 'knowledge', 'textbook', 'learn'],
  green_book: ['read', 'library', 'knowledge', 'study'],
  blue_book: ['read', 'library', 'knowledge', 'learn', 'study'],
  orange_book: ['read', 'library', 'knowledge', 'textbook', 'study'],
  notebook_with_decorative_cover: ['classroom', 'notes', 'record', 'paper', 'study'],
  ledger: ['notes', 'paper'],
  books: ['literature', 'library', 'study'],
  open_book: ['book', 'read', 'library', 'knowledge', 'literature', 'learn', 'study'],
  safety_pin: ['diaper'],
  link: ['rings', 'url'],
  paperclip: ['documents', 'stationery'],
  paperclips: ['documents', 'stationery'],
  scissors: ['stationery', 'cut'],
  triangular_ruler: ['stationery', 'math', 'architect', 'sketch'],
  straight_ruler: ['stationery', 'calculate', 'length', 'math', 'school', 'drawing', 'architect', 'sketch'],
  abacus: ['calculation'],
  pushpin: ['stationery', 'mark', 'here'],
  round_pushpin: ['stationery', 'location', 'map', 'here'],
  triangular_flag_on_post: ['mark', 'milestone', 'place'],
  white_flag: ['losing', 'loser', 'lost', 'surrender', 'give up', 'fail'],
  black_flag: ['pirate'],
  rainbow_flag: [
    'flag',
    'rainbow',
    'pride',
    'gay',
    'lgbt',
    'glbt',
    'queer',
    'homosexual',
    'lesbian',
    'bisexual',
    'transgender',
  ],
  closed_lock_with_key: ['security', 'privacy'],
  lock: ['security', 'password', 'padlock'],
  unlock: ['privacy', 'security'],
  lock_with_ink_pen: ['security', 'secret'],
  pen: ['stationery', 'writing', 'write'],
  fountain_pen: ['stationery', 'writing', 'write'],
  black_nib: ['pen', 'stationery', 'writing', 'write'],
  memo: [
    'write',
    'documents',
    'stationery',
    'pencil',
    'paper',
    'writing',
    'legal',
    'exam',
    'quiz',
    'test',
    'study',
    'compose',
  ],
  pencil2: ['stationery', 'write', 'paper', 'writing', 'school', 'study'],
  crayon: ['drawing', 'creativity'],
  paintbrush: ['drawing', 'creativity', 'art'],
  mag: ['search', 'zoom', 'find', 'detective'],
  mag_right: ['search', 'zoom', 'find', 'detective'],
  heart: ['love', 'like', 'valentines'],
  orange_heart: ['love', 'like', 'affection', 'valentines'],
  yellow_heart: ['love', 'like', 'affection', 'valentines'],
  green_heart: ['love', 'like', 'affection', 'valentines'],
  blue_heart: ['love', 'like', 'affection', 'valentines'],
  purple_heart: ['love', 'like', 'affection', 'valentines'],
  black_heart: ['evil'],
  broken_heart: ['sad', 'sorry', 'break', 'heart', 'heartbreak'],
  heavy_heart_exclamation: ['decoration', 'love'],
  two_hearts: ['love', 'like', 'affection', 'valentines', 'heart'],
  revolving_hearts: ['love', 'like', 'affection', 'valentines'],
  heartbeat: ['love', 'like', 'affection', 'valentines', 'pink', 'heart'],
  heartpulse: ['like', 'love', 'affection', 'valentines', 'pink'],
  sparkling_heart: ['love', 'like', 'affection', 'valentines'],
  cupid: ['love', 'like', 'heart', 'affection', 'valentines'],
  gift_heart: ['love', 'valentines'],
  heart_decoration: ['purple-square', 'love', 'like'],
  peace_symbol: ['hippie'],
  latin_cross: ['christianity'],
  star_and_crescent: ['islam'],
  om: ['hinduism', 'buddhism', 'sikhism', 'jainism'],
  wheel_of_dharma: ['hinduism', 'buddhism', 'sikhism', 'jainism'],
  star_of_david: ['judaism'],
  six_pointed_star: ['purple-square', 'religion', 'jewish', 'hexagram'],
  menorah: ['hanukkah', 'candles', 'jewish'],
  yin_yang: ['balance'],
  orthodox_cross: ['suppedaneum', 'religion'],
  place_of_worship: ['religion', 'church', 'temple', 'prayer'],
  ophiuchus: ['sign', 'purple-square', 'constellation', 'astrology'],
  aries: ['sign', 'purple-square', 'zodiac', 'astrology'],
  taurus: ['purple-square', 'sign', 'zodiac', 'astrology'],
  gemini: ['sign', 'zodiac', 'purple-square', 'astrology'],
  cancer: ['sign', 'zodiac', 'purple-square', 'astrology'],
  leo: ['sign', 'purple-square', 'zodiac', 'astrology'],
  virgo: ['sign', 'zodiac', 'purple-square', 'astrology'],
  libra: ['sign', 'purple-square', 'zodiac', 'astrology'],
  scorpius: ['sign', 'zodiac', 'purple-square', 'astrology', 'scorpio'],
  sagittarius: ['sign', 'zodiac', 'purple-square', 'astrology'],
  capricorn: ['sign', 'zodiac', 'purple-square', 'astrology'],
  aquarius: ['sign', 'purple-square', 'zodiac', 'astrology'],
  pisces: ['purple-square', 'sign', 'zodiac', 'astrology'],
  id: ['purple-square', 'words'],
  atom_symbol: ['science', 'physics', 'chemistry'],
  u7a7a: ['kanji', 'japanese', 'chinese', 'empty', 'sky', 'blue-square'],
  u5272: ['cut', 'divide', 'chinese', 'kanji', 'pink-square'],
  radioactive: ['nuclear', 'danger'],
  biohazard: ['danger'],
  mobile_phone_off: ['mute', 'orange-square', 'silence', 'quiet'],
  vibration_mode: ['orange-square', 'phone'],
  u6709: ['orange-square', 'chinese', 'have', 'kanji'],
  u7121: ['nothing', 'chinese', 'kanji', 'japanese', 'orange-square'],
  u7533: ['chinese', 'japanese', 'kanji', 'orange-square'],
  u55b6: ['japanese', 'opening hours', 'orange-square'],
  u6708: ['chinese', 'month', 'moon', 'japanese', 'orange-square', 'kanji'],
  eight_pointed_black_star: ['orange-square', 'shape', 'polygon'],
  vs: ['words', 'orange-square'],
  accept: ['ok', 'good', 'chinese', 'kanji', 'agree', 'yes', 'orange-circle'],
  white_flower: ['japanese', 'spring'],
  ideograph_advantage: ['chinese', 'kanji', 'obtain', 'get', 'circle'],
  secret: ['privacy', 'chinese', 'sshh', 'kanji', 'red-circle'],
  congratulations: ['chinese', 'kanji', 'japanese', 'red-circle'],
  u5408: ['japanese', 'chinese', 'join', 'kanji', 'red-square'],
  u6e80: ['full', 'chinese', 'japanese', 'red-square', 'kanji'],
  u7981: ['kanji', 'japanese', 'chinese', 'forbidden', 'limit', 'restricted', 'red-square'],
  a: ['red-square', 'alphabet', 'letter'],
  b: ['red-square', 'alphabet', 'letter'],
  ab: ['red-square', 'alphabet'],
  cl: ['alphabet', 'words', 'red-square'],
  o2: ['alphabet', 'red-square', 'letter'],
  sos: ['help', 'red-square', 'words', 'emergency', '911'],
  no_entry: ['limit', 'security', 'privacy', 'bad', 'denied', 'stop', 'circle'],
  name_badge: ['fire', 'forbid'],
  no_entry_sign: ['forbid', 'stop', 'limit', 'denied', 'disallow', 'circle'],
  x: ['no', 'delete', 'remove', 'cancel', 'red'],
  o: ['circle', 'round'],
  stop_sign: ['stop'],
  anger: ['angry', 'mad'],
  hotsprings: ['bath', 'warm', 'relax'],
  no_pedestrians: ['rules', 'crossing', 'walking', 'circle'],
  do_not_litter: ['trash', 'bin', 'garbage', 'circle'],
  no_bicycles: ['cyclist', 'prohibited', 'circle'],
  'non-potable_water': ['drink', 'faucet', 'tap', 'circle'],
  underage: ['18', 'drink', 'pub', 'night', 'minor', 'circle'],
  no_mobile_phones: ['iphone', 'mute', 'circle'],
  exclamation: ['heavy_exclamation_mark', 'danger', 'surprise', 'punctuation', 'wow', 'warning'],
  grey_exclamation: ['surprise', 'punctuation', 'gray', 'wow', 'warning'],
  question: ['doubt', 'confused'],
  grey_question: ['doubts', 'gray', 'huh', 'confused'],
  bangbang: ['exclamation', 'surprise'],
  interrobang: ['wat', 'punctuation', 'surprise'],
  low_brightness: ['sun', 'afternoon', 'warm', 'summer'],
  high_brightness: ['sun', 'light'],
  trident: ['weapon', 'spear'],
  fleur_de_lis: ['decorative', 'scout'],
  part_alternation_mark: ['graph', 'presentation', 'stats', 'business', 'economics', 'bad'],
  warning: ['exclamation', 'wip', 'alert', 'error', 'problem', 'issue'],
  children_crossing: ['school', 'warning', 'danger', 'sign', 'driving', 'yellow-diamond'],
  beginner: ['badge', 'shield'],
  recycle: ['arrow', 'environment', 'garbage', 'trash'],
  u6307: ['chinese', 'point', 'green-square', 'kanji'],
  chart: ['green-square', 'graph', 'presentation', 'stats'],
  sparkle: ['stars', 'green-square', 'awesome', 'good', 'fireworks'],
  eight_spoked_asterisk: ['star', 'sparkle', 'green-square'],
  negative_squared_cross_mark: ['x', 'green-square', 'no', 'deny'],
  white_check_mark: ['green-square', 'ok', 'agree', 'vote', 'election', 'answer', 'tick'],
  diamond_shape_with_a_dot_inside: ['jewel', 'blue', 'gem', 'crystal', 'fancy'],
  cyclone: [
    'weather',
    'swirl',
    'blue',
    'cloud',
    'vortex',
    'spiral',
    'whirlpool',
    'spin',
    'tornado',
    'hurricane',
    'typhoon',
  ],
  loop: ['tape', 'cassette'],
  globe_with_meridians: ['earth', 'international', 'world', 'internet', 'interweb', 'i18n'],
  m: ['alphabet', 'blue-circle', 'letter'],
  atm: ['money', 'sales', 'cash', 'blue-square', 'payment', 'bank'],
  sa: ['japanese', 'blue-square', 'katakana'],
  passport_control: ['custom', 'blue-square'],
  customs: ['passport', 'border', 'blue-square'],
  baggage_claim: ['blue-square', 'airport', 'transport'],
  left_luggage: ['blue-square', 'travel'],
  wheelchair: ['blue-square', 'disabled', 'a11y', 'accessibility'],
  no_smoking: ['cigarette', 'blue-square', 'smell', 'smoke'],
  wc: ['toilet', 'restroom', 'blue-square'],
  parking: ['cars', 'blue-square', 'alphabet', 'letter'],
  potable_water: ['blue-square', 'liquid', 'restroom', 'cleaning', 'faucet'],
  mens: ['toilet', 'restroom', 'wc', 'blue-square', 'gender', 'male'],
  womens: ['purple-square', 'woman', 'female', 'toilet', 'loo', 'restroom', 'gender'],
  baby_symbol: ['orange-square', 'child'],
  restroom: ['blue-square', 'toilet', 'refresh', 'wc', 'gender'],
  put_litter_in_its_place: ['blue-square', 'sign', 'human', 'info'],
  cinema: ['blue-square', 'record', 'film', 'movie', 'curtain', 'stage', 'theater'],
  signal_strength: ['blue-square', 'reception', 'phone', 'internet', 'connection', 'wifi', 'bluetooth', 'bars'],
  koko: ['blue-square', 'here', 'katakana', 'japanese', 'destination'],
  ng: ['blue-square', 'words', 'shape', 'icon'],
  ok: ['good', 'agree', 'yes', 'blue-square'],
  up: ['blue-square', 'above', 'high'],
  cool: ['words', 'blue-square'],
  new: ['blue-square', 'words', 'start'],
  free: ['blue-square', 'words'],
  zero: ['0', 'numbers', 'blue-square', 'null'],
  one: ['blue-square', 'numbers', '1'],
  two: ['numbers', '2', 'prime', 'blue-square'],
  three: ['3', 'numbers', 'prime', 'blue-square'],
  four: ['4', 'numbers', 'blue-square'],
  five: ['5', 'numbers', 'blue-square', 'prime'],
  six: ['6', 'numbers', 'blue-square'],
  seven: ['7', 'numbers', 'blue-square', 'prime'],
  eight: ['8', 'blue-square', 'numbers'],
  nine: ['blue-square', 'numbers', '9'],
  keycap_ten: ['numbers', '10', 'blue-square'],
  asterisk: ['star', 'keycap'],
  eject_button: ['blue-square'],
  arrow_forward: ['blue-square', 'right', 'direction', 'play'],
  pause_button: ['pause', 'blue-square'],
  next_track_button: ['forward', 'next', 'blue-square'],
  stop_button: ['blue-square'],
  record_button: ['blue-square'],
  play_or_pause_button: ['blue-square', 'play', 'pause'],
  previous_track_button: ['backward'],
  fast_forward: ['blue-square', 'play', 'speed', 'continue'],
  rewind: ['play', 'blue-square'],
  twisted_rightwards_arrows: ['blue-square', 'shuffle', 'music', 'random'],
  repeat: ['loop', 'record'],
  repeat_one: ['blue-square', 'loop'],
  arrow_backward: ['blue-square', 'left', 'direction'],
  arrow_up_small: ['blue-square', 'triangle', 'direction', 'point', 'forward', 'top'],
  arrow_down_small: ['blue-square', 'direction', 'bottom'],
  arrow_double_up: ['blue-square', 'direction', 'top'],
  arrow_double_down: ['blue-square', 'direction', 'bottom'],
  arrow_right: ['blue-square', 'next'],
  arrow_left: ['blue-square', 'previous', 'back'],
  arrow_up: ['blue-square', 'continue', 'top', 'direction'],
  arrow_down: ['blue-square', 'direction', 'bottom'],
  arrow_upper_right: ['blue-square', 'point', 'direction', 'diagonal', 'northeast'],
  arrow_lower_right: ['blue-square', 'direction', 'diagonal', 'southeast'],
  arrow_lower_left: ['blue-square', 'direction', 'diagonal', 'southwest'],
  arrow_upper_left: ['blue-square', 'point', 'direction', 'diagonal', 'northwest'],
  arrow_up_down: ['blue-square', 'direction', 'way', 'vertical'],
  left_right_arrow: ['shape', 'direction', 'horizontal', 'sideways'],
  arrows_counterclockwise: ['blue-square', 'sync', 'cycle'],
  arrow_right_hook: ['blue-square', 'return', 'rotate', 'direction'],
  leftwards_arrow_with_hook: ['back', 'return', 'blue-square', 'undo', 'enter'],
  arrow_heading_up: ['blue-square', 'direction', 'top'],
  arrow_heading_down: ['blue-square', 'direction', 'bottom'],
  hash: ['symbol', 'blue-square', 'twitter'],
  information_source: ['blue-square', 'alphabet', 'letter'],
  abc: ['blue-square', 'alphabet'],
  abcd: ['blue-square', 'alphabet'],
  capital_abcd: ['alphabet', 'words', 'blue-square'],
  symbols: ['blue-square', 'music', 'note', 'ampersand', 'percent', 'glyphs', 'characters'],
  musical_note: ['score', 'tone', 'sound'],
  notes: ['music', 'score'],
  wavy_dash: ['draw', 'line', 'moustache', 'mustache', 'squiggle', 'scribble'],
  curly_loop: ['scribble', 'draw', 'shape', 'squiggle'],
  heavy_check_mark: ['ok', 'nike', 'answer', 'yes', 'tick'],
  arrows_clockwise: ['sync', 'cycle', 'round', 'repeat'],
  heavy_plus_sign: ['math', 'calculation', 'addition', 'more', 'increase'],
  heavy_minus_sign: ['math', 'calculation', 'subtract', 'less'],
  heavy_division_sign: ['divide', 'math', 'calculation'],
  heavy_multiplication_x: ['math', 'calculation'],
  infinity: ['forever'],
  heavy_dollar_sign: ['money', 'sales', 'payment', 'currency', 'buck'],
  currency_exchange: ['money', 'sales', 'dollar', 'travel'],
  copyright: ['ip', 'license', 'circle', 'law', 'legal'],
  registered: ['alphabet', 'circle'],
  tm: ['trademark', 'brand', 'law', 'legal'],
  end: ['words', 'arrow'],
  back: ['arrow', 'words', 'return'],
  on: ['arrow', 'words'],
  top: ['words', 'blue-square'],
  soon: ['arrow', 'words'],
  ballot_box_with_check: ['ok', 'agree', 'confirm', 'black-square', 'vote', 'election', 'yes', 'tick'],
  radio_button: ['input', 'old', 'music', 'circle'],
  white_circle: ['shape', 'round'],
  black_circle: ['shape', 'button', 'round'],
  red_circle: ['shape', 'error', 'danger'],
  large_blue_circle: ['shape', 'icon', 'button'],
  small_orange_diamond: ['shape', 'jewel', 'gem'],
  small_blue_diamond: ['shape', 'jewel', 'gem'],
  large_orange_diamond: ['shape', 'jewel', 'gem'],
  large_blue_diamond: ['shape', 'jewel', 'gem'],
  small_red_triangle: ['shape', 'direction', 'up', 'top'],
  black_small_square: ['shape', 'icon'],
  white_small_square: ['shape', 'icon'],
  black_large_square: ['shape', 'icon', 'button'],
  white_large_square: ['shape', 'icon', 'stone', 'button'],
  small_red_triangle_down: ['shape', 'direction', 'bottom'],
  black_medium_square: ['shape', 'button', 'icon'],
  white_medium_square: ['shape', 'stone', 'icon'],
  black_medium_small_square: ['icon', 'shape', 'button'],
  white_medium_small_square: ['shape', 'stone', 'icon', 'button'],
  black_square_button: ['shape', 'input', 'frame'],
  white_square_button: ['shape', 'input'],
  speaker: ['sound', 'volume', 'silence', 'broadcast'],
  sound: ['volume', 'speaker', 'broadcast'],
  loud_sound: ['volume', 'noise', 'noisy', 'speaker', 'broadcast'],
  mute: ['sound', 'volume', 'silence', 'quiet'],
  mega: ['sound', 'speaker', 'volume'],
  loudspeaker: ['volume', 'sound'],
  bell: ['sound', 'notification', 'christmas', 'xmas', 'chime'],
  no_bell: ['sound', 'volume', 'mute', 'quiet', 'silent'],
  black_joker: ['poker', 'cards', 'game', 'play', 'magic'],
  mahjong: ['game', 'play', 'chinese', 'kanji'],
  spades: ['poker', 'cards', 'suits', 'magic'],
  clubs: ['poker', 'cards', 'magic', 'suits'],
  hearts: ['poker', 'cards', 'magic', 'suits'],
  diamonds: ['poker', 'cards', 'magic', 'suits'],
  flower_playing_cards: ['game', 'sunset', 'red'],
  thought_balloon: ['bubble', 'cloud', 'speech', 'thinking', 'dream'],
  right_anger_bubble: ['caption', 'speech', 'thinking', 'mad'],
  speech_balloon: ['bubble', 'words', 'message', 'talk', 'chatting'],
  left_speech_bubble: ['words', 'message', 'talk', 'chatting'],
  clock1: ['time', 'late', 'early', 'schedule'],
  clock2: ['time', 'late', 'early', 'schedule'],
  clock3: ['time', 'late', 'early', 'schedule'],
  clock4: ['time', 'late', 'early', 'schedule'],
  clock5: ['time', 'late', 'early', 'schedule'],
  clock6: ['time', 'late', 'early', 'schedule', 'dawn', 'dusk'],
  clock7: ['time', 'late', 'early', 'schedule'],
  clock8: ['time', 'late', 'early', 'schedule'],
  clock9: ['time', 'late', 'early', 'schedule'],
  clock10: ['time', 'late', 'early', 'schedule'],
  clock11: ['time', 'late', 'early', 'schedule'],
  clock12: ['time', 'noon', 'midnight', 'midday', 'late', 'early', 'schedule'],
  clock130: ['time', 'late', 'early', 'schedule'],
  clock230: ['time', 'late', 'early', 'schedule'],
  clock330: ['time', 'late', 'early', 'schedule'],
  clock430: ['time', 'late', 'early', 'schedule'],
  clock530: ['time', 'late', 'early', 'schedule'],
  clock630: ['time', 'late', 'early', 'schedule'],
  clock730: ['time', 'late', 'early', 'schedule'],
  clock830: ['time', 'late', 'early', 'schedule'],
  clock930: ['time', 'late', 'early', 'schedule'],
  clock1030: ['time', 'late', 'early', 'schedule'],
  clock1130: ['time', 'late', 'early', 'schedule'],
  clock1230: ['time', 'late', 'early', 'schedule'],
  afghanistan: ['af', 'flag', 'nation', 'country', 'banner'],
  aland_islands: ['Åland', 'islands', 'flag', 'nation', 'country', 'banner'],
  albania: ['al', 'flag', 'nation', 'country', 'banner'],
  algeria: ['dz', 'flag', 'nation', 'country', 'banner'],
  american_samoa: ['american', 'ws', 'flag', 'nation', 'country', 'banner'],
  andorra: ['ad', 'flag', 'nation', 'country', 'banner'],
  angola: ['ao', 'flag', 'nation', 'country', 'banner'],
  anguilla: ['ai', 'flag', 'nation', 'country', 'banner'],
  antarctica: ['aq', 'flag', 'nation', 'country', 'banner'],
  antigua_barbuda: ['antigua', 'barbuda', 'flag', 'nation', 'country', 'banner'],
  argentina: ['ar', 'flag', 'nation', 'country', 'banner'],
  armenia: ['am', 'flag', 'nation', 'country', 'banner'],
  aruba: ['aw', 'flag', 'nation', 'country', 'banner'],
  australia: ['au', 'flag', 'nation', 'country', 'banner'],
  austria: ['at', 'flag', 'nation', 'country', 'banner'],
  azerbaijan: ['az', 'flag', 'nation', 'country', 'banner'],
  bahamas: ['bs', 'flag', 'nation', 'country', 'banner'],
  bahrain: ['bh', 'flag', 'nation', 'country', 'banner'],
  bangladesh: ['bd', 'flag', 'nation', 'country', 'banner'],
  barbados: ['bb', 'flag', 'nation', 'country', 'banner'],
  belarus: ['by', 'flag', 'nation', 'country', 'banner'],
  belgium: ['be', 'flag', 'nation', 'country', 'banner'],
  belize: ['bz', 'flag', 'nation', 'country', 'banner'],
  benin: ['bj', 'flag', 'nation', 'country', 'banner'],
  bermuda: ['bm', 'flag', 'nation', 'country', 'banner'],
  bhutan: ['bt', 'flag', 'nation', 'country', 'banner'],
  bolivia: ['bo', 'flag', 'nation', 'country', 'banner'],
  caribbean_netherlands: ['bonaire', 'flag', 'nation', 'country', 'banner'],
  bosnia_herzegovina: ['bosnia', 'herzegovina', 'flag', 'nation', 'country', 'banner'],
  botswana: ['bw', 'flag', 'nation', 'country', 'banner'],
  brazil: ['br', 'flag', 'nation', 'country', 'banner'],
  british_indian_ocean_territory: ['british', 'indian', 'ocean', 'territory', 'flag', 'nation', 'country', 'banner'],
  british_virgin_islands: ['british', 'virgin', 'islands', 'bvi', 'flag', 'nation', 'country', 'banner'],
  brunei: ['bn', 'darussalam', 'flag', 'nation', 'country', 'banner'],
  bulgaria: ['bg', 'flag', 'nation', 'country', 'banner'],
  burkina_faso: ['burkina', 'faso', 'flag', 'nation', 'country', 'banner'],
  burundi: ['bi', 'flag', 'nation', 'country', 'banner'],
  cape_verde: ['cabo', 'verde', 'flag', 'nation', 'country', 'banner'],
  cambodia: ['kh', 'flag', 'nation', 'country', 'banner'],
  cameroon: ['cm', 'flag', 'nation', 'country', 'banner'],
  canada: ['ca', 'flag', 'nation', 'country', 'banner'],
  canary_islands: ['canary', 'islands', 'flag', 'nation', 'country', 'banner'],
  cayman_islands: ['cayman', 'islands', 'flag', 'nation', 'country', 'banner'],
  central_african_republic: ['central', 'african', 'republic', 'flag', 'nation', 'country', 'banner'],
  chad: ['td', 'flag', 'nation', 'country', 'banner'],
  chile: ['flag', 'nation', 'country', 'banner'],
  cn: ['china', 'chinese', 'prc', 'flag', 'country', 'nation', 'banner'],
  christmas_island: ['christmas', 'island', 'flag', 'nation', 'country', 'banner'],
  cocos_islands: ['cocos', 'keeling', 'islands', 'flag', 'nation', 'country', 'banner'],
  colombia: ['co', 'flag', 'nation', 'country', 'banner'],
  comoros: ['km', 'flag', 'nation', 'country', 'banner'],
  congo_brazzaville: ['congo', 'flag', 'nation', 'country', 'banner'],
  congo_kinshasa: ['congo', 'democratic', 'republic', 'flag', 'nation', 'country', 'banner'],
  cook_islands: ['cook', 'islands', 'flag', 'nation', 'country', 'banner'],
  costa_rica: ['costa', 'rica', 'flag', 'nation', 'country', 'banner'],
  croatia: ['hr', 'flag', 'nation', 'country', 'banner'],
  cuba: ['cu', 'flag', 'nation', 'country', 'banner'],
  curacao: ['curaçao', 'flag', 'nation', 'country', 'banner'],
  cyprus: ['cy', 'flag', 'nation', 'country', 'banner'],
  czech_republic: ['cz', 'flag', 'nation', 'country', 'banner'],
  denmark: ['dk', 'flag', 'nation', 'country', 'banner'],
  djibouti: ['dj', 'flag', 'nation', 'country', 'banner'],
  dominica: ['dm', 'flag', 'nation', 'country', 'banner'],
  dominican_republic: ['dominican', 'republic', 'flag', 'nation', 'country', 'banner'],
  ecuador: ['ec', 'flag', 'nation', 'country', 'banner'],
  egypt: ['eg', 'flag', 'nation', 'country', 'banner'],
  el_salvador: ['el', 'salvador', 'flag', 'nation', 'country', 'banner'],
  equatorial_guinea: ['equatorial', 'gn', 'flag', 'nation', 'country', 'banner'],
  eritrea: ['er', 'flag', 'nation', 'country', 'banner'],
  estonia: ['ee', 'flag', 'nation', 'country', 'banner'],
  ethiopia: ['et', 'flag', 'nation', 'country', 'banner'],
  eu: ['european', 'union', 'flag', 'banner'],
  falkland_islands: ['falkland', 'islands', 'malvinas', 'flag', 'nation', 'country', 'banner'],
  faroe_islands: ['faroe', 'islands', 'flag', 'nation', 'country', 'banner'],
  fiji: ['fj', 'flag', 'nation', 'country', 'banner'],
  finland: ['fi', 'flag', 'nation', 'country', 'banner'],
  fr: ['banner', 'flag', 'nation', 'france', 'french', 'country'],
  french_guiana: ['french', 'guiana', 'flag', 'nation', 'country', 'banner'],
  french_polynesia: ['french', 'polynesia', 'flag', 'nation', 'country', 'banner'],
  french_southern_territories: ['french', 'southern', 'territories', 'flag', 'nation', 'country', 'banner'],
  gabon: ['ga', 'flag', 'nation', 'country', 'banner'],
  gambia: ['gm', 'flag', 'nation', 'country', 'banner'],
  georgia: ['ge', 'flag', 'nation', 'country', 'banner'],
  de: ['german', 'nation', 'flag', 'country', 'banner'],
  ghana: ['gh', 'flag', 'nation', 'country', 'banner'],
  gibraltar: ['gi', 'flag', 'nation', 'country', 'banner'],
  greece: ['gr', 'flag', 'nation', 'country', 'banner'],
  greenland: ['gl', 'flag', 'nation', 'country', 'banner'],
  grenada: ['gd', 'flag', 'nation', 'country', 'banner'],
  guadeloupe: ['gp', 'flag', 'nation', 'country', 'banner'],
  guam: ['gu', 'flag', 'nation', 'country', 'banner'],
  guatemala: ['gt', 'flag', 'nation', 'country', 'banner'],
  guernsey: ['gg', 'flag', 'nation', 'country', 'banner'],
  guinea: ['gn', 'flag', 'nation', 'country', 'banner'],
  guinea_bissau: ['gw', 'bissau', 'flag', 'nation', 'country', 'banner'],
  guyana: ['gy', 'flag', 'nation', 'country', 'banner'],
  haiti: ['ht', 'flag', 'nation', 'country', 'banner'],
  honduras: ['hn', 'flag', 'nation', 'country', 'banner'],
  hong_kong: ['hong', 'kong', 'flag', 'nation', 'country', 'banner'],
  hungary: ['hu', 'flag', 'nation', 'country', 'banner'],
  iceland: ['is', 'flag', 'nation', 'country', 'banner'],
  india: ['in', 'flag', 'nation', 'country', 'banner'],
  indonesia: ['flag', 'nation', 'country', 'banner'],
  iran: ['iran,', 'islamic', 'republic', 'flag', 'nation', 'country', 'banner'],
  iraq: ['iq', 'flag', 'nation', 'country', 'banner'],
  ireland: ['ie', 'flag', 'nation', 'country', 'banner'],
  isle_of_man: ['isle', 'man', 'flag', 'nation', 'country', 'banner'],
  israel: ['il', 'flag', 'nation', 'country', 'banner'],
  it: ['italy', 'flag', 'nation', 'country', 'banner'],
  cote_divoire: ['ivory', 'coast', 'flag', 'nation', 'country', 'banner'],
  jamaica: ['jm', 'flag', 'nation', 'country', 'banner'],
  jp: ['japanese', 'nation', 'flag', 'country', 'banner'],
  jersey: ['je', 'flag', 'nation', 'country', 'banner'],
  jordan: ['jo', 'flag', 'nation', 'country', 'banner'],
  kazakhstan: ['kz', 'flag', 'nation', 'country', 'banner'],
  kenya: ['ke', 'flag', 'nation', 'country', 'banner'],
  kiribati: ['ki', 'flag', 'nation', 'country', 'banner'],
  kosovo: ['xk', 'flag', 'nation', 'country', 'banner'],
  kuwait: ['kw', 'flag', 'nation', 'country', 'banner'],
  kyrgyzstan: ['kg', 'flag', 'nation', 'country', 'banner'],
  laos: ['lao', 'democratic', 'republic', 'flag', 'nation', 'country', 'banner'],
  latvia: ['lv', 'flag', 'nation', 'country', 'banner'],
  lebanon: ['lb', 'flag', 'nation', 'country', 'banner'],
  lesotho: ['ls', 'flag', 'nation', 'country', 'banner'],
  liberia: ['lr', 'flag', 'nation', 'country', 'banner'],
  libya: ['ly', 'flag', 'nation', 'country', 'banner'],
  liechtenstein: ['li', 'flag', 'nation', 'country', 'banner'],
  lithuania: ['lt', 'flag', 'nation', 'country', 'banner'],
  luxembourg: ['lu', 'flag', 'nation', 'country', 'banner'],
  macau: ['macao', 'flag', 'nation', 'country', 'banner'],
  macedonia: ['macedonia,', 'flag', 'nation', 'country', 'banner'],
  madagascar: ['mg', 'flag', 'nation', 'country', 'banner'],
  malawi: ['mw', 'flag', 'nation', 'country', 'banner'],
  malaysia: ['my', 'flag', 'nation', 'country', 'banner'],
  maldives: ['mv', 'flag', 'nation', 'country', 'banner'],
  mali: ['ml', 'flag', 'nation', 'country', 'banner'],
  malta: ['mt', 'flag', 'nation', 'country', 'banner'],
  marshall_islands: ['marshall', 'islands', 'flag', 'nation', 'country', 'banner'],
  martinique: ['mq', 'flag', 'nation', 'country', 'banner'],
  mauritania: ['mr', 'flag', 'nation', 'country', 'banner'],
  mauritius: ['mu', 'flag', 'nation', 'country', 'banner'],
  mayotte: ['yt', 'flag', 'nation', 'country', 'banner'],
  mexico: ['mx', 'flag', 'nation', 'country', 'banner'],
  micronesia: ['micronesia,', 'federated', 'states', 'flag', 'nation', 'country', 'banner'],
  moldova: ['moldova,', 'republic', 'flag', 'nation', 'country', 'banner'],
  monaco: ['mc', 'flag', 'nation', 'country', 'banner'],
  mongolia: ['mn', 'flag', 'nation', 'country', 'banner'],
  montenegro: ['me', 'flag', 'nation', 'country', 'banner'],
  montserrat: ['ms', 'flag', 'nation', 'country', 'banner'],
  morocco: ['ma', 'flag', 'nation', 'country', 'banner'],
  mozambique: ['mz', 'flag', 'nation', 'country', 'banner'],
  myanmar: ['mm', 'flag', 'nation', 'country', 'banner'],
  namibia: ['na', 'flag', 'nation', 'country', 'banner'],
  nauru: ['nr', 'flag', 'nation', 'country', 'banner'],
  nepal: ['np', 'flag', 'nation', 'country', 'banner'],
  netherlands: ['nl', 'flag', 'nation', 'country', 'banner'],
  new_caledonia: ['new', 'caledonia', 'flag', 'nation', 'country', 'banner'],
  new_zealand: ['new', 'zealand', 'flag', 'nation', 'country', 'banner'],
  nicaragua: ['ni', 'flag', 'nation', 'country', 'banner'],
  niger: ['ne', 'flag', 'nation', 'country', 'banner'],
  nigeria: ['flag', 'nation', 'country', 'banner'],
  niue: ['nu', 'flag', 'nation', 'country', 'banner'],
  norfolk_island: ['norfolk', 'island', 'flag', 'nation', 'country', 'banner'],
  northern_mariana_islands: ['northern', 'mariana', 'islands', 'flag', 'nation', 'country', 'banner'],
  north_korea: ['north', 'korea', 'nation', 'flag', 'country', 'banner'],
  norway: ['no', 'flag', 'nation', 'country', 'banner'],
  oman: ['om_symbol', 'flag', 'nation', 'country', 'banner'],
  pakistan: ['pk', 'flag', 'nation', 'country', 'banner'],
  palau: ['pw', 'flag', 'nation', 'country', 'banner'],
  palestinian_territories: ['palestine', 'palestinian', 'territories', 'flag', 'nation', 'country', 'banner'],
  panama: ['pa', 'flag', 'nation', 'country', 'banner'],
  papua_new_guinea: ['papua', 'new', 'guinea', 'flag', 'nation', 'country', 'banner'],
  paraguay: ['py', 'flag', 'nation', 'country', 'banner'],
  peru: ['pe', 'flag', 'nation', 'country', 'banner'],
  philippines: ['ph', 'flag', 'nation', 'country', 'banner'],
  pitcairn_islands: ['pitcairn', 'flag', 'nation', 'country', 'banner'],
  poland: ['pl', 'flag', 'nation', 'country', 'banner'],
  portugal: ['pt', 'flag', 'nation', 'country', 'banner'],
  puerto_rico: ['puerto', 'rico', 'flag', 'nation', 'country', 'banner'],
  qatar: ['qa', 'flag', 'nation', 'country', 'banner'],
  reunion: ['réunion', 'flag', 'nation', 'country', 'banner'],
  romania: ['ro', 'flag', 'nation', 'country', 'banner'],
  ru: ['russian', 'federation', 'flag', 'nation', 'country', 'banner'],
  rwanda: ['rw', 'flag', 'nation', 'country', 'banner'],
  st_barthelemy: ['saint', 'barthélemy', 'flag', 'nation', 'country', 'banner'],
  st_helena: ['saint', 'helena', 'ascension', 'tristan', 'cunha', 'flag', 'nation', 'country', 'banner'],
  st_kitts_nevis: ['saint', 'kitts', 'nevis', 'flag', 'nation', 'country', 'banner'],
  st_lucia: ['saint', 'lucia', 'flag', 'nation', 'country', 'banner'],
  st_pierre_miquelon: ['saint', 'pierre', 'miquelon', 'flag', 'nation', 'country', 'banner'],
  st_vincent_grenadines: ['saint', 'vincent', 'grenadines', 'flag', 'nation', 'country', 'banner'],
  samoa: ['ws', 'flag', 'nation', 'country', 'banner'],
  san_marino: ['san', 'marino', 'flag', 'nation', 'country', 'banner'],
  sao_tome_principe: ['sao', 'tome', 'principe', 'flag', 'nation', 'country', 'banner'],
  saudi_arabia: ['flag', 'nation', 'country', 'banner'],
  senegal: ['sn', 'flag', 'nation', 'country', 'banner'],
  serbia: ['rs', 'flag', 'nation', 'country', 'banner'],
  seychelles: ['sc', 'flag', 'nation', 'country', 'banner'],
  sierra_leone: ['sierra', 'leone', 'flag', 'nation', 'country', 'banner'],
  singapore: ['sg', 'flag', 'nation', 'country', 'banner'],
  sint_maarten: ['sint', 'maarten', 'dutch', 'flag', 'nation', 'country', 'banner'],
  slovakia: ['sk', 'flag', 'nation', 'country', 'banner'],
  slovenia: ['si', 'flag', 'nation', 'country', 'banner'],
  solomon_islands: ['solomon', 'islands', 'flag', 'nation', 'country', 'banner'],
  somalia: ['so', 'flag', 'nation', 'country', 'banner'],
  south_africa: ['south', 'africa', 'flag', 'nation', 'country', 'banner'],
  south_georgia_south_sandwich_islands: [
    'south',
    'georgia',
    'sandwich',
    'islands',
    'flag',
    'nation',
    'country',
    'banner',
  ],
  kr: ['south', 'korea', 'nation', 'flag', 'country', 'banner'],
  south_sudan: ['south', 'sd', 'flag', 'nation', 'country', 'banner'],
  es: ['spain', 'flag', 'nation', 'country', 'banner'],
  sri_lanka: ['sri', 'lanka', 'flag', 'nation', 'country', 'banner'],
  sudan: ['sd', 'flag', 'nation', 'country', 'banner'],
  suriname: ['sr', 'flag', 'nation', 'country', 'banner'],
  swaziland: ['sz', 'flag', 'nation', 'country', 'banner'],
  sweden: ['se', 'flag', 'nation', 'country', 'banner'],
  switzerland: ['ch', 'flag', 'nation', 'country', 'banner'],
  syria: ['syrian', 'arab', 'republic', 'flag', 'nation', 'country', 'banner'],
  taiwan: ['tw', 'flag', 'nation', 'country', 'banner'],
  tajikistan: ['tj', 'flag', 'nation', 'country', 'banner'],
  tanzania: ['tanzania,', 'united', 'republic', 'flag', 'nation', 'country', 'banner'],
  thailand: ['th', 'flag', 'nation', 'country', 'banner'],
  timor_leste: ['timor', 'leste', 'flag', 'nation', 'country', 'banner'],
  togo: ['tg', 'flag', 'nation', 'country', 'banner'],
  tokelau: ['tk', 'flag', 'nation', 'country', 'banner'],
  tonga: ['to', 'flag', 'nation', 'country', 'banner'],
  trinidad_tobago: ['trinidad', 'tobago', 'flag', 'nation', 'country', 'banner'],
  tunisia: ['tn', 'flag', 'nation', 'country', 'banner'],
  tr: ['turkey', 'flag', 'nation', 'country', 'banner'],
  turkmenistan: ['flag', 'nation', 'country', 'banner'],
  turks_caicos_islands: ['turks', 'caicos', 'islands', 'flag', 'nation', 'country', 'banner'],
  tuvalu: ['flag', 'nation', 'country', 'banner'],
  uganda: ['ug', 'flag', 'nation', 'country', 'banner'],
  ukraine: ['ua', 'flag', 'nation', 'country', 'banner'],
  united_arab_emirates: ['united', 'arab', 'emirates', 'flag', 'nation', 'country', 'banner'],
  uk: [
    'united',
    'kingdom',
    'great',
    'britain',
    'northern',
    'ireland',
    'flag',
    'nation',
    'country',
    'banner',
    'british',
    'UK',
    'english',
    'england',
    'union jack',
  ],
  england: ['flag', 'english'],
  scotland: ['flag', 'scottish'],
  wales: ['flag', 'welsh'],
  us: ['united', 'states', 'america', 'flag', 'nation', 'country', 'banner'],
  us_virgin_islands: ['virgin', 'islands', 'us', 'flag', 'nation', 'country', 'banner'],
  uruguay: ['uy', 'flag', 'nation', 'country', 'banner'],
  uzbekistan: ['uz', 'flag', 'nation', 'country', 'banner'],
  vanuatu: ['vu', 'flag', 'nation', 'country', 'banner'],
  vatican_city: ['vatican', 'city', 'flag', 'nation', 'country', 'banner'],
  venezuela: ['ve', 'bolivarian', 'republic', 'flag', 'nation', 'country', 'banner'],
  vietnam: ['viet', 'nam', 'flag', 'nation', 'country', 'banner'],
  wallis_futuna: ['wallis', 'futuna', 'flag', 'nation', 'country', 'banner'],
  western_sahara: ['western', 'sahara', 'flag', 'nation', 'country', 'banner'],
  yemen: ['ye', 'flag', 'nation', 'country', 'banner'],
  zambia: ['zm', 'flag', 'nation', 'country', 'banner'],
  zimbabwe: ['zw', 'flag', 'nation', 'country', 'banner'],
  united_nations: ['un', 'flag', 'banner'],
  pirate_flag: ['skull', 'crossbones', 'flag', 'banner'],
}
