/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BroadcastStatus
 */
export interface BroadcastStatus {
    /**
     * 
     * @type {string}
     * @memberof BroadcastStatus
     */
    'url'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BroadcastStatus
     */
    'is_active'?: boolean;
}

