/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyboardModifiers
 */
export interface KeyboardModifiers {
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'shift'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'capslock'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'control'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'alt'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'numlock'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'meta'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'super'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KeyboardModifiers
     */
    'altgr'?: boolean;
}

