/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemberProfile } from './member-profile';

/**
 * 
 * @export
 * @interface MemberData
 */
export interface MemberData {
    /**
     * 
     * @type {string}
     * @memberof MemberData
     */
    'id'?: string;
    /**
     * 
     * @type {MemberProfile}
     * @memberof MemberData
     */
    'profile'?: MemberProfile;
}

