/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemberBulkDelete
 */
export interface MemberBulkDelete {
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberBulkDelete
     */
    'ids'?: Array<string>;
}

