/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemberProfile
 */
export interface MemberProfile {
    /**
     * 
     * @type {string}
     * @memberof MemberProfile
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'is_admin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_login'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_connect'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_watch'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_host'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_share_media'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_access_clipboard'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'sends_inactive_cursor'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfile
     */
    'can_see_inactive_cursors'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MemberProfile
     */
    'plugins'?: { [key: string]: any; };
}

