/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemberProfile } from './member-profile';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionState } from './session-state';

/**
 * 
 * @export
 * @interface SessionData
 */
export interface SessionData {
    /**
     * 
     * @type {string}
     * @memberof SessionData
     */
    'id'?: string;
    /**
     * Only if cookie authentication is disabled.
     * @type {string}
     * @memberof SessionData
     */
    'token'?: string;
    /**
     * 
     * @type {MemberProfile}
     * @memberof SessionData
     */
    'profile'?: MemberProfile;
    /**
     * 
     * @type {SessionState}
     * @memberof SessionData
     */
    'state'?: SessionState;
}

