/* tslint:disable */
/* eslint-disable */
/**
 * n.eko REST API
 * Next Gen Renderer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    'private_mode'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    'locked_controls'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    'implicit_hosting'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    'inactive_cursors'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    'merciful_reconnect'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Settings
     */
    'plugins'?: { [key: string]: any; };
}

