#
# Custom Google Chrome image for n.eko
#
# This Dockerfile inherits from the official n.eko google-chrome image.
# You can add your own custom commands here to install additional software
# or make other modifications to the image.
#

ARG BASE_IMAGE=ghcr.io/m1k1o/neko/google-chrome:latest
FROM $BASE_IMAGE

#
# Add your custom commands here.
#
# For example, to install a browser extension, you can use:
#
# RUN mkdir -p /etc/opt/chrome/policies/managed/
# RUN echo '{ "ExtensionInstallForcelist": [ "<extension_id>;https://clients2.google.com/service/update2/crx" ] }' > /etc/opt/chrome/policies/managed/policies.json
#
