FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends apache2-utils netcat-openbsd squid \
    && htpasswd -bc /etc/squid/passwords proxy-user proxy-password \
    && rm -rf /var/lib/apt/lists/*

COPY squid.conf /etc/squid/squid.conf
CMD ["squid", "-N", "-f", "/etc/squid/squid.conf"]
