http_port 3128

auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm Neko proxy integration test
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_access deny all

cache deny all
access_log none
cache_log /var/log/squid/cache.log
pid_filename none
