package keys

const KEY_0 = 48
const KEY_1 = 49
const KEY_2 = 50
const KEY_3 = 51
const KEY_4 = 52
const KEY_5 = 53
const KEY_6 = 54
const KEY_7 = 55
const KEY_8 = 56
const KEY_9 = 57

const KEY_A = 65
const KEY_B = 66
const KEY_C = 67
const KEY_D = 68
const KEY_E = 69
const KEY_F = 70
const KEY_G = 71
const KEY_H = 72
const KEY_I = 73
const KEY_J = 74
const KEY_K = 75
const KEY_L = 76
const KEY_M = 77
const KEY_N = 78
const KEY_O = 79
const KEY_P = 80
const KEY_Q = 81
const KEY_R = 82
const KEY_S = 83
const KEY_T = 84
const KEY_U = 85
const KEY_V = 86
const KEY_W = 87
const KEY_X = 88
const KEY_Y = 89
const KEY_Z = 90

const KEY_NUMPAD0 = 96
const KEY_NUMPAD1 = 97
const KEY_NUMPAD2 = 98
const KEY_NUMPAD3 = 99
const KEY_NUMPAD4 = 100
const KEY_NUMPAD5 = 101
const KEY_NUMPAD6 = 102
const KEY_NUMPAD7 = 103
const KEY_NUMPAD8 = 104
const KEY_NUMPAD9 = 105

const KEY_F1 = 112
const KEY_F2 = 113
const KEY_F3 = 114
const KEY_F4 = 115
const KEY_F5 = 116
const KEY_F6 = 117
const KEY_F7 = 118
const KEY_F8 = 119
const KEY_F9 = 120
const KEY_F10 = 121
const KEY_F11 = 122
const KEY_F12 = 123

const KEY_BACK_SPACE = 8
const KEY_TAB = 9
const KEY_ENTER = 13
const KEY_ENTER_ALT = 14
const KEY_SHIFT = 16
const KEY_CONTROL = 17
const KEY_ALT = 18
const KEY_ESCAPE = 27
const KEY_SPACE = 32
const KEY_PAGE_UP = 33
const KEY_PAGE_DOWN = 34
const KEY_END = 35
const KEY_LEFT = 37
const KEY_UP = 38
const KEY_RIGHT = 39
const KEY_DOWN = 40
const KEY_DELETE = 46
const KEY_SEMICOLON = 59
const KEY_SEMICOLON_ALT = 186
const KEY_EQUALS = 61
const KEY_EQUALS_ALT = 187
const KEY_MULTIPLY = 106
const KEY_ADD = 107
const KEY_SEPARATOR = 108
const KEY_SUBTRACT = 109
const KEY_SUBTRACT_ALT = 189
const KEY_DECIMAL = 110
const KEY_DIVIDE = 111
const KEY_COMMA = 188
const KEY_PERIOD = 190
const KEY_SLASH = 191
const KEY_BACK_QUOTE = 192
const KEY_BACK_SLASH = 220
const KEY_OPEN_BRACKET = 219
const KEY_CLOSE_BRACKET = 221
const KEY_QUOTE = 222

var Keyboard = map[int]string{}

func init() {
	Keyboard[KEY_A] = "a"
	Keyboard[KEY_B] = "b"
	Keyboard[KEY_C] = "c"
	Keyboard[KEY_D] = "d"
	Keyboard[KEY_E] = "e"
	Keyboard[KEY_F] = "f"
	Keyboard[KEY_G] = "g"
	Keyboard[KEY_H] = "h"
	Keyboard[KEY_I] = "i"
	Keyboard[KEY_J] = "j"
	Keyboard[KEY_K] = "k"
	Keyboard[KEY_L] = "l"
	Keyboard[KEY_M] = "m"
	Keyboard[KEY_N] = "n"
	Keyboard[KEY_O] = "o"
	Keyboard[KEY_P] = "p"
	Keyboard[KEY_Q] = "q"
	Keyboard[KEY_R] = "r"
	Keyboard[KEY_S] = "s"
	Keyboard[KEY_T] = "t"
	Keyboard[KEY_U] = "u"
	Keyboard[KEY_V] = "v"
	Keyboard[KEY_W] = "w"
	Keyboard[KEY_X] = "x"
	Keyboard[KEY_Y] = "y"
	Keyboard[KEY_Z] = "z"

	Keyboard[KEY_0] = "0"
	Keyboard[KEY_1] = "1"
	Keyboard[KEY_2] = "2"
	Keyboard[KEY_3] = "3"
	Keyboard[KEY_4] = "4"
	Keyboard[KEY_5] = "5"
	Keyboard[KEY_6] = "6"
	Keyboard[KEY_7] = "7"
	Keyboard[KEY_8] = "8"
	Keyboard[KEY_9] = "9"

	Keyboard[KEY_NUMPAD0] = "0"
	Keyboard[KEY_NUMPAD1] = "1"
	Keyboard[KEY_NUMPAD2] = "2"
	Keyboard[KEY_NUMPAD3] = "3"
	Keyboard[KEY_NUMPAD4] = "4"
	Keyboard[KEY_NUMPAD5] = "5"
	Keyboard[KEY_NUMPAD6] = "6"
	Keyboard[KEY_NUMPAD7] = "7"
	Keyboard[KEY_NUMPAD8] = "8"
	Keyboard[KEY_NUMPAD9] = "9"

	Keyboard[KEY_F1] = "f1"
	Keyboard[KEY_F2] = "f2"
	Keyboard[KEY_F3] = "f3"
	Keyboard[KEY_F4] = "f4"
	Keyboard[KEY_F5] = "f5"
	Keyboard[KEY_F6] = "f6"
	Keyboard[KEY_F7] = "f7"
	Keyboard[KEY_F8] = "f8"
	Keyboard[KEY_F9] = "f9"
	Keyboard[KEY_F10] = "f10"
	Keyboard[KEY_F11] = "f11"
	Keyboard[KEY_F12] = "f12"

	Keyboard[KEY_QUOTE] = "'"
	Keyboard[KEY_COMMA] = ","
	Keyboard[KEY_PERIOD] = "."
	Keyboard[KEY_SEMICOLON] = ";"
	Keyboard[KEY_SEMICOLON_ALT] = ";"
	Keyboard[KEY_SLASH] = "/"
	Keyboard[KEY_BACK_SLASH] = "\\"
	Keyboard[KEY_BACK_QUOTE] = "`"
	Keyboard[KEY_OPEN_BRACKET] = "["
	Keyboard[KEY_CLOSE_BRACKET] = "]"
	Keyboard[KEY_EQUALS] = "="
	Keyboard[KEY_EQUALS_ALT] = "="
	Keyboard[KEY_MULTIPLY] = "*"
	Keyboard[KEY_ADD] = "+"
	Keyboard[KEY_SEPARATOR] = "."
	Keyboard[KEY_SUBTRACT] = "-"
	Keyboard[KEY_SUBTRACT_ALT] = "-"
	Keyboard[KEY_DECIMAL] = "."
	Keyboard[KEY_DIVIDE] = "/"
	Keyboard[KEY_BACK_SPACE] = "backspace"
	Keyboard[KEY_DELETE] = "delete"
	Keyboard[KEY_ENTER] = "enter"
	Keyboard[KEY_ENTER_ALT] = "enter"
	Keyboard[KEY_TAB] = "tab"
	Keyboard[KEY_ESCAPE] = "escape"
	Keyboard[KEY_UP] = "up"
	Keyboard[KEY_DOWN] = "down"
	Keyboard[KEY_RIGHT] = "right"
	Keyboard[KEY_LEFT] = "left"
	Keyboard[KEY_END] = "end"
	Keyboard[KEY_PAGE_UP] = "pageup"
	Keyboard[KEY_PAGE_DOWN] = "pagedown"
	Keyboard[KEY_ALT] = "alt"
	Keyboard[KEY_CONTROL] = "control"
	Keyboard[KEY_SHIFT] = "shift"
	Keyboard[KEY_SPACE] = "space"
}
