name: Build and Push to GHCR for Nvidia

on:
  push:
    tags:
      - 'v*'

jobs:
  check-latest:
    name: Check if Latest Version
    uses: ./.github/workflows/check_latest.yml

  build-base:
    name: Base Image
    needs: check-latest
    uses: ./.github/workflows/image_base.yml
    with:
      flavor: nvidia
      platforms: linux/amd64
      dockerfile: Dockerfile.nvidia
      latest: ${{ needs.check-latest.outputs.is_latest == 'true' }}
      latest_major: ${{ needs.check-latest.outputs.is_latest_major == 'true' }}
    secrets: inherit

  build-app:
    name: App Image
    uses: ./.github/workflows/image_app.yml
    needs: [build-base, check-latest]
    strategy:
      # Will build all images even if some fail.
      fail-fast: false
      matrix:
        include:
          - name: firefox
            dockerfile: Dockerfile.nvidia
          - name: brave
            dockerfile: Dockerfile.nvidia
          - name: chromium
            dockerfile: Dockerfile.nvidia
          - name: google-chrome
            dockerfile: Dockerfile.nvidia
          - name: microsoft-edge
            dockerfile: Dockerfile.nvidia
    with:
      name: ${{ matrix.name }}
      flavor: nvidia
      platforms: ${{ matrix.platforms }}
      dockerfile: ${{ matrix.dockerfile }}
      latest: ${{ needs.check-latest.outputs.is_latest == 'true' }}
      latest_major: ${{ needs.check-latest.outputs.is_latest_major == 'true' }}
    secrets: inherit
