#!/bin/sh
cd "$(dirname "$0")"

# start component watch
docker run --rm -it \
    --user "$(id -u):$(id -g)" \
    --volume "${PWD}/../:/app" \
    --entrypoint="npm" \
    --workdir="/app" \
    node:24-trixie-slim run build
