#!/bin/sh
cd "$(dirname "$0")"

# start component watch
docker run --rm -it \
    --user "$(id -u):$(id -g)" \
    --volume "${PWD}/../:/app" \
    --entrypoint="/bin/bash" \
    --workdir="/app" \
    node:18-bullseye-slim
